import {createRoom} from './soap-film-room.js';
const $=id=>document.getElementById(id),demo=$('sf-demo'),canvas=$('sf-canvas'),view=$('sf-view');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches,visible=true,offscreen=false,room,device,context,target,display,displayGroup,raf=0,last=0,clock=0,disposed=false,starting=false;
let sample={x:.5,y:.5},quality='medium',seed='51a9f17c',error=null,width=0,height=0;
const renderCosts=[],queueCosts=[],finalGPUCosts=[];let adaptive=true,timingInterval=60;let frame=0,query,resolve,read,pending=false;const listeners=[];
const on=(el,event,handler,options)=>{el.addEventListener(event,handler,options);listeners.push(()=>el.removeEventListener(event,handler,options));};
const record=(a,v)=>{a.push(v);if(a.length>240)a.shift();};const stats=a=>{if(!a.length)return null;const b=[...a].sort((a,b)=>a-b);return{medianMs:b[Math.floor(b.length*.5)],p95Ms:b[Math.floor(b.length*.95)],samples:b.length};};
function fail(message){error=message;stop();room?.dispose();room=null;target?.destroy();target=null;canvas.hidden=true;$('sf-still').hidden=false;$('sf-status').textContent=message+' Showing a computed initial-state still.';$('sf-status').hidden=false;demo.setAttribute('aria-busy','false');$('sf-play').disabled=true;$('sf-restart').disabled=true;for(const id of ['sf-apply','sf-quality','sf-angle','sf-seed'])$(id).disabled=true;$('sf-readings').replaceChildren();$('sf-phase').textContent='Still';$('sf-sample').textContent='Live measurements unavailable';$('sf-runtime').textContent='Still: spectral rendering of the initial model';query?.destroy();resolve?.destroy();read?.destroy();context?.unconfigure();device?.destroy();}
function stop(){cancelAnimationFrame(raf);raf=0;last=0;}
function active(){return !disposed&&!starting&&room&&visible&&!offscreen;}
function wake(){if(active()&&!raf){last=0;raf=requestAnimationFrame(loop);}}
function resize(){if(!device||!room)return;const r=view.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,1.5);const w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(w===width&&h===height)return;width=w;height=h;canvas.width=w;canvas.height=h;target?.destroy();target=device.createTexture({size:[w,h],format:'rgba16float',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_SRC});displayGroup=device.createBindGroup({layout:display.getBindGroupLayout(0),entries:[{binding:0,resource:target.createView()}]});room.resize({width:w,height:h,dpr});wake();}
function readings(){if(!room)return;const s=room.snapshot(),d=s.diagnostics,p=room.sampleAt(sample.x,sample.y);$('sf-sample').textContent=p.hole?'Open film':`${sample.x===.5&&sample.y===.5?'Center':'Sample'} ${Math.round(p.thicknessNm)} nm`;
 $('sf-phase').textContent=paused?'Paused':d.state==='rupturing'?'Opening':d.state==='rest'?'Rest':s.simulationTime<12?'Warming':'Draining';
 if(adaptive&&s.performance.solverCPU?.samples>50&&s.performance.solverCPU.p95Ms>26)room.setWorkBudget(1);
 if(adaptive&&s.performance.solverCPU?.samples>100&&s.performance.solverCPU.p95Ms>32&&room.reduceQuality()){$('sf-quality').value=room.snapshot().quality;$('sf-runtime').textContent='Grid reduced for this device; model parameters preserved';}
 const nl=v=>(v*1e12).toFixed(1)+' nL',perf=s.performance.solverCPU;
 const values=[['Thickness',d.thicknessRangeNm.map(Math.round).join(' to ')+' nm'],['Temperature',d.temperatureRangeC.map(v=>v.toFixed(1)).join(' to ')+' °C'],['Grid / step',s.grid.join(' × ')+' / '+s.numericalStepCount],['Viscosity / diffusivity','1.0e-6 / 1.2e-6 m²/s'],['Pressure equation residual',d.pressureResidualMetersInverseSecondsInverse==null?'Not measured':d.pressureResidualMetersInverseSecondsInverse.toExponential(2)+' 1/(m s)'],['Max divergence',d.divergenceMaxPerSecond.toExponential(2)+' 1/s'],['Film / retracted rim',nl(d.filmVolumeM3)+' / '+nl(d.rimVolumeM3)],['Evaporated / drained',nl(d.evaporatedM3)+' / '+nl(d.drainedM3)],['Supplied / removed on reset',nl(d.replenishedM3)+' / '+nl(d.resetDiscardedM3)],['Mass ledger error',nl(d.massBalanceErrorM3)],['Model clock / diagnostic age',s.simulationTime.toFixed(1)+' s / '+s.diagnosticAgeSeconds.toFixed(1)+' s'],['CPU solver median / p95',perf?perf.medianMs.toFixed(1)+' / '+perf.p95Ms.toFixed(1)+' ms':'Measuring']];
 $('sf-readings').replaceChildren(...values.map(([a,b])=>{const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=a;dd.textContent=b;div.append(dt,dd);return div;}));
}
function draw(){const start=performance.now(),encoder=device.createCommandEncoder();room.render({encoder,targetView:target.createView(),width,height,exposure:12});const timed=query&&!pending&&frame++%timingInterval===0;
 const pass=encoder.beginRenderPass({colorAttachments:[{view:context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store'}],...(timed?{timestampWrites:{querySet:query,beginningOfPassWriteIndex:0,endOfPassWriteIndex:1}}:{})});pass.setPipeline(display);pass.setBindGroup(0,displayGroup);pass.draw(3);pass.end();
 if(timed){pending=true;encoder.resolveQuerySet(query,0,2,resolve,0);encoder.copyBufferToBuffer(resolve,0,read,0,16);}device.queue.submit([encoder.finish()]);room.afterSubmit();record(renderCosts,performance.now()-start);
 if(timed){const submitted=performance.now();read.mapAsync(GPUMapMode.READ).then(()=>{const t=new BigUint64Array(read.getMappedRange());record(finalGPUCosts,Number(t[1]-t[0])/1e6);read.unmap();record(queueCosts,performance.now()-submitted);}).catch(()=>{}).finally(()=>{pending=false;});}
}
function loop(now){raf=0;if(!active())return;try{const dt=last?Math.min(.1,(now-last)/1000):0;last=now;if(!paused){clock+=dt;room.step({dtSeconds:dt,elapsedSeconds:clock,scoreSeconds:clock});}draw();if(Math.floor(now/500)!==Math.floor((now-dt*1000)/500))readings();if(!paused)raf=requestAnimationFrame(loop);}catch(e){fail(e.message);}}
async function initialize(){starting=true;stop();try{
 if(!navigator.gpu)throw Error('WebGPU is unavailable.');const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error('No WebGPU adapter is available.');
 device=await adapter.requestDevice({requiredFeatures:adapter.features.has('timestamp-query')?['timestamp-query']:[]});
 device.addEventListener('uncapturederror',e=>fail('WebGPU validation error: '+e.error.message));device.lost.then(info=>{if(!disposed&&!error)fail('The graphics device was lost: '+info.message);});
 window.__soapFilmAdapter={...adapter.info,description:adapter.info.description||'Not exposed',vendor:adapter.info.vendor,architecture:adapter.info.architecture,isFallbackAdapter:adapter.info.isFallbackAdapter??null};
 context=canvas.getContext('webgpu');if(!context)throw Error('A WebGPU canvas could not be created.');context.configure({device,format:navigator.gpu.getPreferredCanvasFormat(),alphaMode:'opaque'});
 const module=device.createShaderModule({code:`@group(0) @binding(0) var image:texture_2d<f32>;
 @vertex fn vs(@builtin(vertex_index) i:u32)->@builtin(position) vec4f {var a=array<vec2f,3>(vec2f(-1,-1),vec2f(3,-1),vec2f(-1,3));return vec4f(a[i],0,1);}
 fn encode(c:vec3f)->vec3f{return select(12.92*c,1.055*pow(c,vec3f(1.0/2.4))-.055,c>vec3f(.0031308));}
 @fragment fn fs(@builtin(position) pos:vec4f)->@location(0) vec4f {let c=max(textureLoad(image,vec2i(pos.xy),0).rgb,vec3f(0));return vec4f(encode(1-exp(-c)),1);}`});
 display=await device.createRenderPipelineAsync({layout:'auto',vertex:{module,entryPoint:'vs'},fragment:{module,entryPoint:'fs',targets:[{format:navigator.gpu.getPreferredCanvasFormat()}]}});
 if(device.features.has('timestamp-query')){query=device.createQuerySet({type:'timestamp',count:2});resolve=device.createBuffer({size:16,usage:GPUBufferUsage.QUERY_RESOLVE|GPUBufferUsage.COPY_SRC});read=device.createBuffer({size:16,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});}
 room=await createRoom({device,seed,quality});if(disposed){room.dispose();return;}starting=false;$('sf-status').hidden=true;demo.setAttribute('aria-busy','false');$('sf-play').disabled=false;$('sf-restart').disabled=false;$('sf-play').textContent=paused?'Play':'Pause';resize();readings();wake();
 }catch(e){starting=false;fail(e.message);}}
on($('sf-play'),'click',()=>{paused=!paused;$('sf-play').textContent=paused?'Play':'Pause';readings();wake();});
on($('sf-restart'),'click',()=>{room?.restart();clock=0;readings();wake();});
on($('sf-instruments-toggle'),'click',()=>{const open=$('sf-instruments').hidden;$('sf-instruments').hidden=!open;$('sf-instruments-toggle').setAttribute('aria-expanded',String(open));readings();});
on($('sf-angle'),'input',e=>{room?.setViewingAngle(Number(e.target.value));$('sf-angle-value').textContent=e.target.value+'°';wake();});
on($('sf-apply'),'click',async()=>{if(!device||starting)return;if(!$('sf-seed').checkValidity()){$('sf-seed').reportValidity();return;}starting=true;adaptive=false;stop();quality=$('sf-quality').value;seed=$('sf-seed').value.toLowerCase();try{const next=await createRoom({device,seed,quality});room?.dispose();room=next;room.setViewingAngle(Number($('sf-angle').value));room.resize({width,height,dpr:Math.min(devicePixelRatio,1.5)});clock=0;starting=false;readings();wake();}catch(e){starting=false;fail(e.message);}});
async function fullscreen(){if(document.fullscreenElement){await document.exitFullscreen();}else if(demo.classList.contains('sf-expanded')){demo.classList.remove('sf-expanded');$('sf-fullscreen').textContent='Fullscreen';}else{try{await demo.requestFullscreen();}catch{demo.classList.add('sf-expanded');$('sf-fullscreen').textContent='Exit fullscreen';}}resize();}
on($('sf-fullscreen'),'click',fullscreen);on(document,'fullscreenchange',()=>{$('sf-fullscreen').textContent=document.fullscreenElement?'Exit fullscreen':'Fullscreen';resize();});
on(canvas,'keydown',e=>{if(e.code==='Space'){e.preventDefault();$('sf-play').click();}if(e.key.toLowerCase()==='f')fullscreen();});on(document,'keydown',e=>{if(e.key==='Escape'&&demo.classList.contains('sf-expanded')){demo.classList.remove('sf-expanded');$('sf-fullscreen').textContent='Fullscreen';resize();}});
on(canvas,'pointerdown',point);on(canvas,'pointermove',e=>{if(e.pointerType==='mouse'||e.buttons)point(e);});function point(e){const r=canvas.getBoundingClientRect(),side=Math.min(r.width*.82,r.height*.84);const x=(e.clientX-r.left-r.width/2)/side+.5,y=(e.clientY-r.top-r.height/2)/side+.5;if(x>=0&&x<=1&&y>=0&&y<=1){sample={x,y};readings();}}
on(document,'visibilitychange',()=>{visible=!document.hidden;if(!visible)stop();else wake();});on(reduced,'change',e=>{if(e.matches){paused=true;$('sf-play').textContent='Play';readings();wake();}});
const observer=new IntersectionObserver(entries=>{offscreen=!entries[0].isIntersecting;if(offscreen)stop();else wake();},{threshold:.01});observer.observe(view);const resizer=new ResizeObserver(resize);resizer.observe(view);
function dispose(){disposed=true;stop();observer.disconnect();resizer.disconnect();listeners.forEach(f=>f());room?.dispose();target?.destroy();query?.destroy();resolve?.destroy();read?.destroy();context?.unconfigure();device?.destroy();}
on(window,'pagehide',dispose);
window.SoapFilm={setAdaptive(value){adaptive=value;},async benchmarkRender(count=120){timingInterval=1;room.setTimingInterval(1);for(let k=0;k<count;k++){draw();await device.queue.onSubmittedWorkDone();await new Promise(r=>requestAnimationFrame(r));}timingInterval=60;room.setTimingInterval(60);},snapshot:()=>room?{...room.snapshot(),host:{paused,visible,offscreen,loopRunning:!!raf,error,canvas:[width,height],renderCPU:stats(renderCosts),finalDisplayGPU:stats(finalGPUCosts),queueReadbackLatency:stats(queueCosts)},adapter:window.__soapFilmAdapter}: {error,host:{paused,visible,offscreen}},debugReadback:()=>room?.debugReadback(),
 // Test harness accelerates wall-clock pacing, preserving every solver step.
 async advanceSteps(count){if(!room)throw Error('No live room');stop();for(let k=0;k<count;k++){room.step({dtSeconds:.04,elapsedSeconds:clock,scoreSeconds:clock});clock+=.04;if(k%100===0)await new Promise(r=>setTimeout(r,0));}await room.debugReadback();draw();readings();wake();},room:()=>room,device:()=>device,dispose};
initialize();
