import {createRoom} from './undertow-room.js?v=1';
import {displayShader} from './undertow-shaders.js?v=1';
const el=id=>document.getElementById('undertow-'+id),demo=el('demo'),stage=el('stage'),canvas=el('canvas'),status=el('status'),play=el('play'),restart=el('restart'),listeners=[];
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),url=new URL(location.href),errors=[];
let manualPause=reduced.matches,onScreen=true,room,device,context,display,scene,sceneGroup,frame=0,lastTime=0,initializing=false,disposed=false,generation=0,measuring=false,lastMeasure=0;
let quality=url.searchParams.get('quality')||'medium',seed=url.searchParams.get('seed')||'5eedc0de1234abcd';
if(!['low','medium','high'].includes(quality))quality='medium';if(!/^[0-9a-f]{16}$/i.test(seed))seed='5eedc0de1234abcd';el('quality').value=quality;el('seed').value=seed;
function listen(target,event,fn){target.addEventListener(event,fn);listeners.push(()=>target.removeEventListener(event,fn));}
function active(){return !disposed&&!initializing&&!!room&&!manualPause&&onScreen&&document.visibilityState==='visible';}
function fallback(message){room?.dispose();room=null;cancelAnimationFrame(frame);frame=0;canvas.hidden=true;el('still').hidden=false;status.textContent=message+' Saved fluid snapshot shown; live flow is unavailable.';status.classList.add('undertow-error');demo.setAttribute('aria-busy','false');play.disabled=restart.disabled=true;}
function ratio(rect){return Math.min(devicePixelRatio,2,2560/Math.max(rect.width,rect.height,1),Math.sqrt(4194304/Math.max(rect.width*rect.height,1)));}
function resize(){if(!device||!context||disposed)return;const rect=stage.getBoundingClientRect(),dpr=ratio(rect),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(w===canvas.width&&h===canvas.height&&scene)return;canvas.width=w;canvas.height=h;scene?.destroy();scene=device.createTexture({size:[w,h],format:'rgba16float',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.RENDER_ATTACHMENT});sceneGroup=device.createBindGroup({layout:display.getBindGroupLayout(0),entries:[{binding:0,resource:scene.createView()},{binding:1,resource:device.createSampler({minFilter:'linear',magFilter:'linear'})}]});room?.resize({width:w,height:h,dpr});draw();}
function draw(){if(!room||!scene||disposed)return;const e=device.createCommandEncoder();room.render({encoder:e,targetView:scene.createView(),width:canvas.width,height:canvas.height,exposure:1.35});const p=e.beginRenderPass({colorAttachments:[{view:context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:{r:0,g:0,b:0,a:1}}]});p.setPipeline(display);p.setBindGroup(0,sceneGroup);p.draw(3);p.end();device.queue.submit([e.finish()]);}
function animate(t){frame=0;if(!active())return;const dt=lastTime?Math.min((t-lastTime)/1000,.1):1/60;lastTime=t;room.step({dtSeconds:dt});draw();if(room.snapshot().numericalFault){manualPause=true;status.textContent=room.snapshot().numericalFault;status.classList.add('undertow-error');sync();return;}if(t-lastMeasure>4000&&!measuring){lastMeasure=t;measure();}frame=requestAnimationFrame(animate);}
function sync(){play.textContent=manualPause?'Play':'Pause';play.setAttribute('aria-pressed',String(!manualPause));el('hint').textContent=manualPause?'Paused / Space to play':'Drag to stir';if(!active()){cancelAnimationFrame(frame);frame=0;lastTime=0;room?.setPointer({active:false,vx:0,vy:0});}else if(!frame){lastTime=0;frame=requestAnimationFrame(animate);}instruments();}
async function measure(){if(!room||measuring)return;measuring=true;const current=room;try{await current.measure();if(room===current)instruments();}catch(e){if(room===current&&!disposed){errors.push(e.message);fallback(e.message);}}finally{measuring=false;}}
function instruments(){if(!room)return;const s=room.snapshot(),d=s.diagnostics,fmt=(v,digits=4)=>Number.isFinite(v)?v.toFixed(digits):'Preparing';const rows=[['Fluid time',fmt(s.simulationTime,2)],['Steps',s.numericalStepCount],['Flow grid',s.parameters.velocityGrid.join(' × ')],['Dye grid',s.parameters.dyeGrid.join(' × ')],['Divergence RMS',d?.divergenceRms?.toExponential(2)??'Preparing'],['Peak speed',fmt(d?.maxSpeed)],['Mean kinetic energy',fmt(d?.meanKineticEnergy,5)],['Dye range',fmt(d?.dyeMin,3)+' to '+fmt(d?.dyeMax,3)],['Step queue time',fmt(s.medianStepQueueWallMs,1)+' ms'],['Measured step',d?.measuredStep??'Preparing'],['Time step','1/60'],['Seed',s.seed]];
 el('readouts').replaceChildren(...rows.map(([label,value])=>{const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;div.append(dt,dd);return div;}));el('instrument-note').textContent='Pressure is solved on the periodic grid using a Fourier transform. Dye transport is bounded to neighboring source values before replenishment. A busy GPU slows fluid time; it does not enlarge the time step. Measurements update every four seconds while playing.';}
async function start(){if(initializing||disposed)return;initializing=true;const id=++generation;cancelAnimationFrame(frame);frame=0;room?.dispose();room=null;play.disabled=restart.disabled=true;status.textContent='Starting the flow...';demo.setAttribute('aria-busy','true');lastTime=0;
 try{if(!device){if(!navigator.gpu)throw Error('This browser has no WebGPU.');const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error('No WebGPU adapter is available.');device=await adapter.requestDevice();window.__undertowAdapter={vendor:adapter.info.vendor,architecture:adapter.info.architecture,description:adapter.info.description};device.addEventListener('uncapturederror',event=>{errors.push(event.error.message);fallback('GPU validation failed: '+event.error.message);});device.lost.then(info=>{if(!disposed&&info.reason!=='destroyed')fallback('The GPU device was lost.');});context=canvas.getContext('webgpu');const format=navigator.gpu.getPreferredCanvasFormat();context.configure({device,format,alphaMode:'opaque'});const m=device.createShaderModule({code:displayShader});display=await device.createRenderPipelineAsync({layout:'auto',vertex:{module:m,entryPoint:'vertex'},fragment:{module:m,entryPoint:'fragment',targets:[{format}]}});}
 const next=await createRoom({device,quality,seed,assetBaseURL:new URL('../assets/visualizer/undertow/',import.meta.url).href});if(disposed||id!==generation){next.dispose();return;}room=next;
 // Seeded burn-in gives the opening view actual advected curls.
 await room.advanceSteps(720);if(disposed||id!==generation)return;status.textContent='';status.classList.remove('undertow-error');canvas.hidden=false;el('still').hidden=true;play.disabled=restart.disabled=false;demo.setAttribute('aria-busy','false');resize();draw();instruments();
 }catch(e){errors.push(e.message);fallback(e.message);}finally{initializing=false;sync();}}
async function fullscreen(){if(document.fullscreenElement){await document.exitFullscreen();return;}if(demo.classList.contains('undertow-pseudo-fullscreen')){demo.classList.remove('undertow-pseudo-fullscreen');document.body.style.overflow='';resize();return;}try{await demo.requestFullscreen();}catch{demo.classList.add('undertow-pseudo-fullscreen');document.body.style.overflow='hidden';resize();}}
listen(play,'click',()=>{manualPause=!manualPause;sync();draw();});listen(el('instruments-toggle'),'click',()=>{const open=el('instruments').hidden;el('instruments').hidden=!open;el('instruments-toggle').setAttribute('aria-expanded',String(open));if(open)measure();instruments();});
listen(restart,'click',()=>{const value=el('seed').value.trim().toLowerCase();if(!/^[0-9a-f]{16}$/.test(value)){el('seed').setCustomValidity('Enter exactly 16 hexadecimal digits.');el('seed').reportValidity();return;}el('seed').setCustomValidity('');seed=value;quality=el('quality').value;const next=new URL(location.href);next.searchParams.set('seed',seed);next.searchParams.set('quality',quality);history.replaceState(null,'',next);start();});listen(el('seed'),'input',()=>el('seed').setCustomValidity(''));
listen(el('fullscreen'),'click',fullscreen);listen(document,'fullscreenchange',resize);listen(document,'visibilitychange',sync);listen(reduced,'change',()=>{if(reduced.matches){manualPause=true;sync();}});
listen(document,'keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.code==='Space'&&(e.target===canvas||demo.contains(e.target))){e.preventDefault();manualPause=!manualPause;sync();draw();}if(e.key.toLowerCase()==='f'&&demo.contains(e.target)){e.preventDefault();fullscreen();}if(e.key==='Escape'&&demo.classList.contains('undertow-pseudo-fullscreen')){demo.classList.remove('undertow-pseudo-fullscreen');document.body.style.overflow='';resize();}});
let drag=null;
function pointerPosition(e){const b=canvas.getBoundingClientRect();return {x:2*(e.clientX-b.left)/b.width,y:(e.clientY-b.top)/b.height};}
listen(canvas,'pointerdown',e=>{if(!room||manualPause)return;const pos=pointerPosition(e);drag={id:e.pointerId,...pos,t:e.timeStamp};canvas.setPointerCapture(e.pointerId);room.setPointer({...pos,active:true,vx:0,vy:0,color:room.snapshot().simulationTime*.65});el('hint').textContent='Stirring';});
listen(canvas,'pointermove',e=>{if(drag?.id!==e.pointerId)return;const pos=pointerPosition(e),dt=Math.max(.016,(e.timeStamp-drag.t)/1000),clamp=v=>Math.max(-2,Math.min(2,v));room?.setPointer({...pos,active:true,vx:clamp((pos.x-drag.x)/dt),vy:clamp((pos.y-drag.y)/dt)});drag={id:e.pointerId,...pos,t:e.timeStamp};});
for(const name of ['pointerup','pointercancel','lostpointercapture'])listen(canvas,name,()=>{drag=null;room?.setPointer({active:false,vx:0,vy:0});el('hint').textContent=manualPause?'Paused / Space to play':'Drag to stir';});
const observer=new ResizeObserver(resize);observer.observe(stage);const intersection=new IntersectionObserver(entries=>{onScreen=entries[0].isIntersecting;sync();});intersection.observe(demo);
function dispose(){if(disposed)return;disposed=true;generation++;cancelAnimationFrame(frame);listeners.splice(0).forEach(fn=>fn());observer.disconnect();intersection.disconnect();room?.dispose();scene?.destroy();context?.unconfigure();device?.destroy();}
listen(window,'pagehide',e=>{if(e.persisted){onScreen=false;sync();}else dispose();});listen(window,'pageshow',()=>{onScreen=true;sync();});
window.__undertow={snapshot:()=>({...room?.snapshot(),initializing,manualPause,onScreen,active:active(),errors:errors.slice()}),pause(){manualPause=true;sync();},play(){manualPause=false;sync();},async advanceSteps(count){manualPause=true;sync();await room.advanceSteps(count);draw();instruments();return room.snapshot();},debugReadback:async()=>{const v=await room.debugReadback();return {...v,velocity:Array.from(v.velocity),dye:Array.from(v.dye)};},setPointer:value=>room?.setPointer(value),dispose};
start();
