import {fluidShader,projectShader,dyeShader,renderShader} from './undertow-shaders.js?v=1';
import {modes,seedValue,DT,divergence,rms} from './undertow-model.js?v=1';
export const roomInfo={apiVersion:1,id:'undertow',title:'Undertow',model:'Forced incompressible 2D flow and passive dye on a periodic MAC grid',representativeScaleMeters:null,scaleMeaning:'Dimensionless domain, 2 by 1. No physical calibration.',sources:['https://developer.nvidia.com/gpugems/gpugems/part-vi-beyond-triangles/chapter-38-fast-fluid-dynamics-simulation-gpu','https://physbam.stanford.edu/papers/stanford2006-09.pdf']};
export async function createFlowGPU({device,n=128,dyeSize=512,seed='5eedc0de1234abcd'}){
 if(!device||![16,32,64,128,256].includes(n))throw Error('A WebGPU device and a power-of-two MAC grid are required.');
 const owned=[],B=GPUBufferUsage,make=(size,usage,label)=>{const b=device.createBuffer({size,usage,label});owned.push(b);return b;};
 try {
 const storage=(size,label)=>make(size,B.STORAGE|B.COPY_SRC|B.COPY_DST,label),uniform=(size,label)=>make(size,B.UNIFORM|B.COPY_DST,label);
 const velocity=storage(n*n*8,'Undertow projected MAC velocity'),temporary=storage(n*n*8,'Undertow transported velocity'),fftA=storage(n*n*8,'Undertow FFT A'),fftB=storage(n*n*8,'Undertow FFT B');
 const dye=[storage(dyeSize*dyeSize*16,'Undertow dye A'),storage(dyeSize*dyeSize*16,'Undertow dye B')],forward=storage(dyeSize*dyeSize*16,'Undertow forward dye');
 const params=uniform(80,'Undertow fixed-step parameters'),initial=uniform(192,'Undertow initial stream function'),forcing=uniform(192,'Undertow forcing stream function');
 function modeData(source){const data=new Float32Array(48);source.forEach((a,i)=>{data.set(a.slice(0,4),i*4);data[24+4*i]=a[4];});return data;}
 device.queue.writeBuffer(initial,0,modeData(modes(seed)));device.queue.writeBuffer(forcing,0,modeData(modes(seed,true)));
 const layout=(entries)=>device.createBindGroupLayout({entries:entries.map((type,binding)=>({binding,visibility:GPUShaderStage.COMPUTE,buffer:{type}}))});
 const fluidLayout=layout(['uniform','read-only-storage','storage','uniform']),projectLayout=layout(['uniform','read-only-storage','read-only-storage','storage']),dyeLayout=layout(['uniform','read-only-storage','read-only-storage','read-only-storage','storage']);
 const makeGroup=(layout,buffers)=>device.createBindGroup({layout,entries:buffers.map((buffer,binding)=>({binding,resource:{buffer}}))});
 async function module(code){const m=device.createShaderModule({code});const errors=(await m.getCompilationInfo()).messages.filter(x=>x.type==='error');if(errors.length)throw Error(errors.map(x=>x.message).join('\n'));return m;}
 const [fm,pm,dm,rm]=await Promise.all([module(fluidShader),module(projectShader),module(dyeShader),module(renderShader)]);
 async function pipeline(m,layout,name){return device.createComputePipelineAsync({layout:device.createPipelineLayout({bindGroupLayouts:[layout]}),compute:{module:m,entryPoint:name}});}
 const fluid={};for(const name of ['initialize','advectVelocity','divergence','bitReverse','butterfly','poisson'])fluid[name]=await pipeline(fm,fluidLayout,name);
 const project=await pipeline(pm,projectLayout,'project'),dyeP={};for(const name of ['initializeDye','advectDye','correctDye'])dyeP[name]=await pipeline(dm,dyeLayout,name);
 const fg=(src,dst,u=params,m=forcing)=>makeGroup(fluidLayout,[u,src,dst,m]);
 const reverseParams=uniform(80,'Undertow FFT bit reversal');device.queue.writeBuffer(reverseParams,0,new Uint32Array([n,Math.log2(n),0,0]));
 const initializeGroup=fg(temporary,velocity,params,initial),advectGroup=fg(velocity,temporary),divGroup=fg(temporary,fftA),reverseGroup=fg(fftA,fftB,reverseParams),poissonGroup=fg(fftB,fftA),projectGroup=makeGroup(projectLayout,[params,fftB,temporary,velocity]);
 const log=Math.log2(n),fftStages=[];
 for(const sign of [-1,1])for(let axis=0;axis<2;axis++)for(let stage=0;stage<log;stage++){
  const u=uniform(80,'Undertow FFT butterfly'),data=new ArrayBuffer(80);new Uint32Array(data).set([n,log,axis,2**stage]);new Float32Array(data)[6]=sign;device.queue.writeBuffer(u,0,data);
  const k=axis*log+stage;fftStages.push({sign,group:k%2===0?fg(fftB,fftA,u):fg(fftA,fftB,u)});
 }
 // 2*log(N) stages is even, so every transform finishes in B.
 const dg=(src,orig,dst)=>makeGroup(dyeLayout,[params,velocity,src,orig,dst]);
 const dyeInitialize=dg(forward,dye[1],dye[0]),advectDye=dye.map(a=>dg(a,a,forward)),correctDye=dye.map((a,i)=>dg(forward,a,dye[1-i]));
 const view=uniform(16,'Undertow render view'),render=await device.createRenderPipelineAsync({layout:'auto',vertex:{module:rm,entryPoint:'vertex'},fragment:{module:rm,entryPoint:'fragment',targets:[{format:'rgba16float'}]}});
 const renderGroups=dye.map(buffer=>device.createBindGroup({layout:render.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:view}},{binding:1,resource:{buffer}}]}));
 let steps=0,dyeIndex=0,destroyed=false,pointer={x:1,y:.5,active:false,vx:0,vy:0,color:0};
 function writeParams(){const bytes=new ArrayBuffer(80),u=new Uint32Array(bytes),f=new Float32Array(bytes);u.set([n,dyeSize,0,0]);f.set([steps*DT,DT,0,0],4);f.set([pointer.x,pointer.y,pointer.active?1:0,pointer.color],8);f.set([pointer.vx,pointer.vy,0,0],12);f[16]=(seedValue(seed)/4294967296)*Math.PI*2;device.queue.writeBuffer(params,0,bytes);}
 function dispatch(e,pipe,group,count=n*n,timestamps){const p=e.beginComputePass(timestamps?{timestampWrites:timestamps}:{});p.setPipeline(pipe);p.setBindGroup(0,group);p.dispatchWorkgroups(Math.ceil(count/64));p.end();}
 function pressureSolve(e){dispatch(e,fluid.bitReverse,reverseGroup);for(const s of fftStages)if(s.sign===-1)dispatch(e,fluid.butterfly,s.group);dispatch(e,fluid.poisson,poissonGroup);dispatch(e,fluid.bitReverse,reverseGroup);for(const s of fftStages)if(s.sign===1)dispatch(e,fluid.butterfly,s.group);dispatch(e,project,projectGroup);}
 writeParams();let encoder=device.createCommandEncoder();dispatch(encoder,fluid.initialize,initializeGroup);dispatch(encoder,dyeP.initializeDye,dyeInitialize,dyeSize*dyeSize);device.queue.submit([encoder.finish()]);await device.queue.onSubmittedWorkDone();
 function step({query=null}={}){if(destroyed)return;writeParams();const e=device.createCommandEncoder();dispatch(e,fluid.advectVelocity,advectGroup,n*n,query?{querySet:query,beginningOfPassWriteIndex:0}:undefined);dispatch(e,fluid.divergence,divGroup);pressureSolve(e);dispatch(e,dyeP.advectDye,advectDye[dyeIndex],dyeSize*dyeSize);dispatch(e,dyeP.correctDye,correctDye[dyeIndex],dyeSize*dyeSize,query?{querySet:query,endOfPassWriteIndex:1}:undefined);device.queue.submit([e.finish()]);dyeIndex=1-dyeIndex;steps++;}
 function draw({encoder,targetView,width,height,exposure=1.25,query=null}){device.queue.writeBuffer(view,0,new Float32Array([width,height,dyeSize,exposure]));const p=encoder.beginRenderPass({...(query?{timestampWrites:{querySet:query,beginningOfPassWriteIndex:0,endOfPassWriteIndex:1}}:{}),colorAttachments:[{view:targetView,clearValue:{r:0,g:0,b:0,a:1},loadOp:'clear',storeOp:'store'}]});p.setPipeline(render);p.setBindGroup(0,renderGroups[dyeIndex]);p.draw(3);p.end();}
 async function read(buffer){const staging=device.createBuffer({size:buffer.size,usage:B.MAP_READ|B.COPY_DST});try{const e=device.createCommandEncoder();e.copyBufferToBuffer(buffer,0,staging,0,buffer.size);device.queue.submit([e.finish()]);await staging.mapAsync(GPUMapMode.READ);return new Float32Array(staging.getMappedRange().slice(0));}finally{staging.destroy();}}
 return {n,dyeSize,step,render:draw,get steps(){return steps;},setPointer(value){pointer={...pointer,...value};},memoryBytes:owned.reduce((s,b)=>s+b.size,0),async debugReadback(){return {velocity:await read(velocity),dye:await read(dye[dyeIndex]),steps};},async projectFixture(values){if(values.length!==n*n*2)throw Error('Wrong MAC fixture size');device.queue.writeBuffer(temporary,0,values);const e=device.createCommandEncoder();dispatch(e,fluid.divergence,divGroup);pressureSolve(e);device.queue.submit([e.finish()]);return read(velocity);},dispose(){destroyed=true;owned.forEach(b=>b.destroy());}};
 }catch(e){owned.forEach(b=>b.destroy());throw e;}
}
export async function createRoom({device,quality='medium',seed='5eedc0de1234abcd',assetBaseURL}){
 const sizes={low:[64,384],medium:[128,512],high:[256,1024]};if(!sizes[quality])throw Error('Quality must be low, medium or high.');
 let gpu;try{gpu=await createFlowGPU({device,n:sizes[quality][0],dyeSize:sizes[quality][1],seed});}catch(e){throw Error('Undertow could not initialize: '+e.message);}
 let busy=null,reading=null,disposed=false,accumulator=0,ambient=0,diagnostics=null,fault=null,lastCost=null;const costs=[];
 function step({dtSeconds}){if(disposed||fault)return;ambient+=Math.min(.1,Math.max(0,dtSeconds));accumulator=Math.min(DT*2,accumulator+Math.min(.1,Math.max(0,dtSeconds)));if(accumulator+1e-10<DT||busy)return;accumulator-=DT;const start=performance.now();gpu.step();busy=device.queue.onSubmittedWorkDone().then(()=>{lastCost=performance.now()-start;costs.push(lastCost);if(costs.length>120)costs.shift();}).catch(e=>{fault=e.message;}).finally(()=>{busy=null;});}
 async function collectMeasurement(){const {velocity,dye}=await gpu.debugReadback(),div=divergence(velocity,gpu.n);let kinetic=0,speed=0,min=Infinity,max=-Infinity,mass=[0,0,0];for(let i=0;i<velocity.length;i+=2){const v=velocity[i]**2+velocity[i+1]**2;kinetic+=v*.5/(gpu.n**2);speed=Math.max(speed,Math.sqrt(v));}for(let i=0;i<dye.length;i++)if(i%4!==3){min=Math.min(min,dye[i]);max=Math.max(max,dye[i]);mass[i%4]+=dye[i]/(gpu.dyeSize**2);}diagnostics={measuredStep:gpu.steps,divergenceRms:rms(div),maxSpeed:speed,meanKineticEnergy:kinetic,dyeMin:min,dyeMax:max,meanDye:mass};if(!Number.isFinite(kinetic+speed+min+max)||max>1.00001||min<-.00001||diagnostics.divergenceRms>.001)fault='The solver stopped after an invalid measurement. Restart the flow.';return diagnostics;}
 async function measure(){if(disposed)return diagnostics;if(reading)return reading;reading=collectMeasurement();try{return await reading;}finally{reading=null;}}
 return {resize(){},step,render:args=>gpu.render(args),setPointer:value=>gpu.setPointer(value),snapshot(){const sorted=costs.slice().sort((a,b)=>a-b);return {...roomInfo,quality,seed,numericalStepCount:gpu.steps,simulationTime:gpu.steps*DT,simulationTimeUnits:'dimensionless fluid time',ambientSeconds:ambient,parameters:{velocityGrid:[gpu.n,gpu.n],dyeGrid:[gpu.dyeSize,gpu.dyeSize],domain:[2,1],dt:DT,viscosity:.000004,linearDrag:.10,transport:'RK2 semi-Lagrangian velocity, bounded MacCormack dye',pressure:'Periodic discrete Laplacian solved with 2D radix-2 FFT',forcing:'Discrete curl of six stream-function modes',dyeSources:'Initial bands, weak replenishment, pointer injection'},memory:{roomBuffersBytes:gpu.memoryBytes},seedProvenance:{seed,source:'offline fixed replayable seed',crossDeviceReplay:'f32 transcendental results may differ'},assetBaseURL:String(assetBaseURL??''),diagnosticsAvailable:!!diagnostics,diagnosticAgeSteps:diagnostics?gpu.steps-diagnostics.measuredStep:null,diagnostics,numericalFault:fault,busy:!!busy,lastStepQueueWallMs:lastCost,medianStepQueueWallMs:sorted[Math.floor(sorted.length/2)]??null};},measure,async waitForIdle(){await Promise.allSettled([busy,reading].filter(Boolean));},async advanceSteps(count){if(busy)await busy;for(let i=0;i<count;i++){gpu.step();await device.queue.onSubmittedWorkDone();}return measure();},async debugReadback(){if(busy)await busy;return gpu.debugReadback();},dispose(){disposed=true;const release=()=>gpu.dispose();if(busy||reading)Promise.allSettled([busy,reading].filter(Boolean)).then(release);else release();}};
}
