/* lab-skins.js — three component TREATMENTS (Soft / Sharp / Editorial), each a
   cohesive design system in the LOCKED palette (green bg, parchment, gold) and the
   three locked fonts (Century Supra / Segoe UI / Commit Mono). Plus the shared
   unified component markup the three treatments style. Consumed by components-lab.html. */

window.LAB_UNIFIED = {
  hero: '<header class="u-hero"><p class="u-eyebrow">Field guide</p><h1 class="u-title">How Long Can You Live?</h1><p class="u-dek">The hard wall at 120 is unproven, the records are riddled with fraud, and the thing that actually adds years is the one nobody calls a hack.</p><p class="u-meta">28 sources <span class="u-sep">·</span> 25 min read</p></header>',
  h2: '<h2 class="u-h2">The wall that isn’t</h2>',
  lead: '<p class="u-lead">There is supposed to be a hard wall around 120, and eating less is supposed to be the only real lever. The evidence says something stranger. The <a class="u-link" href="#">cleanest datasets</a> keep showing a flat mortality hazard beyond the extremes, which is <strong>not</strong> what a hard limit would predict.</p>',
  figure: '<figure class="u-figure"><img class="u-figure-img" src="assets/thumbs/how-long-can-you-live.jpg" alt="An ancient bristlecone pine at dusk."><figcaption class="u-figure-cap">A bristlecone pine, nearly five thousand years old.</figcaption></figure>',
  callout: '<aside class="u-callout"><p class="u-callout-k">The honest goal</p><p class="u-callout-body">Not to find the cheat code for 120. It is to not get cheated out of 85.</p></aside>',
  debate: '<div class="u-debate"><p class="u-debate-q">Is the plateau real, or a mirage?</p><div class="u-debate-sides"><div class="u-side u-side-a"><h4 class="u-side-h">It is real</h4><p class="u-side-p">The cleanest datasets show a flat hazard beyond the extremes.</p></div><div class="u-side u-side-b"><h4 class="u-side-h">It is a mirage</h4><p class="u-side-p">A higher-standard cleaning shows no plateau at all.</p></div></div><p class="u-take"><strong>My read:</strong> truly open.</p></div>',
  checklist: '<ul class="u-checks"><li class="u-check u-use"><strong>Daily movement.</strong> A merely good routine kept for decades.</li><li class="u-check u-meh"><strong>Caloric restriction.</strong> Real in mice, unproven in people.</li><li class="u-check u-skip"><strong>Most longevity supplements.</strong> Evidence thin to nonexistent.</li></ul>',
  statinline: '<div class="u-stats"><div class="u-stat"><span class="u-fig">120</span><span class="u-fig-lbl">proposed hard cap, disputed</span></div><div class="u-stat"><span class="u-fig">82%</span><span class="u-fig-lbl">of 110+ records that fail an audit</span></div><div class="u-stat"><span class="u-fig">7</span><span class="u-fig-lbl">verified supercentenarians with papers</span></div></div>',
  statcards: '<div class="u-statcards"><div class="u-statcard"><span class="u-statcard-fig">120</span><span class="u-statcard-lbl">proposed hard cap, disputed</span></div><div class="u-statcard"><span class="u-statcard-fig">82%</span><span class="u-statcard-lbl">of 110+ records that fail an audit</span></div><div class="u-statcard"><span class="u-statcard-fig">7</span><span class="u-statcard-lbl">verified supercentenarians with papers</span></div></div>',
  bignum: '<div class="u-bignum"><span class="u-bignum-fig">82<span class="u-bignum-u">%</span></span><span class="u-bignum-cap">of people recorded as 110 or older have no birth certificate that survives an audit.</span><span class="u-bignum-src">Newman, 2019</span></div>',
  strip: '<div class="u-strip"><span class="u-strip-item"><b>~20 yrs</b> the program ran</span><span class="u-strip-item"><b>122</b> the oldest verified age</span><span class="u-strip-item"><b>7</b> with papers</span><span class="u-strip-item"><b>0</b> proven past 130</span></div>',
  pq: '<blockquote class="u-pq">Whatever the lab effect was, it produced nothing useful.<cite class="u-pq-cite">A skeptic, 1995</cite></blockquote>',
  blockquote: '<blockquote class="u-quote"><p>The honest goal is not to find the cheat code for 120. It is to not get cheated out of 85.</p></blockquote>',
  divider: '<hr class="u-divider">',
  sechead: '<div class="u-sechead"><p class="u-sechead-k">Chapter two</p><h2 class="u-sechead-h">What actually moves the needle</h2></div>',
  cite: '<p class="u-citep">A clean reconstruction puts the real number near forty. <span class="u-src"><a href="#">the roll</a></span> <span class="u-grade u-grade-a">solid</span> <span class="u-grade u-grade-c">contested</span></p>',
  footnote: '<p class="u-fnp">The one paper claiming a hard cap was rebutted five times in its own journal.<sup class="u-cite"><a href="#">1</a></sup> The plateau is, at best, unsettled.<sup class="u-cite"><a href="#">2</a></sup></p>',
  table: '<table class="u-table"><thead><tr><th>Lever</th><th>Years added</th><th>Evidence</th></tr></thead><tbody><tr><td>Daily movement</td><td class="u-num">~3 to 7</td><td>strong</td></tr><tr class="u-feature"><td>Real social connection</td><td class="u-num">~5+</td><td>strong</td></tr><tr><td>Caloric restriction</td><td class="u-num">?</td><td>mixed in humans</td></tr></tbody></table>',
  cards: '<div class="u-cards"><div class="u-card"><h4 class="u-card-h">Move</h4><p class="u-card-p">A merely good routine, kept for decades, beats a perfect one you quit.</p></div><div class="u-card"><h4 class="u-card-h">Sleep</h4><p class="u-card-p">Boring, and it outperforms most supplements.</p></div><div class="u-card"><h4 class="u-card-h">Connect</h4><p class="u-card-p">The one nobody calls a hack.</p></div></div>',
  entries: '<div class="u-entries"><article class="u-entry"><span class="u-entry-num">No. 01</span><h3 class="u-entry-h">The book said a hundred. There were about forty.</h3><p class="u-entry-p">The best reconstruction of the roll puts roughly 41 sober.</p></article><article class="u-entry"><span class="u-entry-num">No. 02</span><h3 class="u-entry-h">The plateau thins out under scrutiny.</h3><p class="u-entry-p">Clean the registry harder and it tends to vanish.</p></article></div>',
  steps: '<ol class="u-steps"><li class="u-step"><span class="u-step-h">Blind the target.</span><p class="u-step-p">You never know what you are looking at.</p></li><li class="u-step"><span class="u-step-h">Work a fixed sequence.</span><p class="u-step-p">Structure beats the flash of insight.</p></li></ol>',
  toc: '<nav class="u-toc"><p class="u-toc-k">What is inside</p><ul class="u-toc-list"><li><a class="u-toc-row" href="#"><span class="u-toc-name"><span class="u-toc-n">01</span>The wall that isn’t</span><span class="u-toc-m">8 min</span></a></li><li><a class="u-toc-row" href="#"><span class="u-toc-name"><span class="u-toc-n">02</span>What moves the needle</span><span class="u-toc-m">6 min</span></a></li><li><a class="u-toc-row" href="#"><span class="u-toc-name"><span class="u-toc-n">03</span>How to read a record</span><span class="u-toc-m">5 min</span></a></li></ul></nav>',
  collapse: '<details class="u-collapse" open><summary class="u-collapse-s">The full list, 28 sources</summary><ol class="u-collapse-list"><li><b>Newman SJ (2019).</b> Errors in supercentenarian records. <a href="#">journals.plos.org</a></li><li><b>Gavrilov &amp; Gavrilova.</b> Mortality at extreme ages. <a href="#">demographic-research.org</a></li></ol></details>',
  dossier: '<div class="u-dossier"><figure class="u-dossier-media"><img class="u-dossier-img" src="assets/thumbs/how-long-can-you-live.jpg" alt="A bristlecone pine."><figcaption class="u-dossier-cap">No. 01 · Bristlecone pine</figcaption></figure><div class="u-dossier-body"><p class="u-dossier-eyebrow">the oldest</p><h3 class="u-dossier-name">Methuselah</h3><div class="u-dossier-stat"><span class="u-dossier-fig">4,855</span><span class="u-dossier-figlbl">years old, and still growing</span></div><p class="u-dossier-lead">The tree keeps almost no living tissue, which may be exactly why it lasts.</p></div></div>',
  defs: '<dl class="u-defs"><dt class="u-defs-t">Centenarian</dt><dd class="u-defs-d">Someone who has reached 100.</dd><dt class="u-defs-t">Supercentenarian</dt><dd class="u-defs-d">Someone verified at 110 or older. There are very few.</dd></dl>',
  leaderboard: '<div class="u-board"><p class="u-board-k">Oldest verified humans</p><ol class="u-board-list"><li class="u-board-row"><span class="u-board-name">Jeanne Calment <i>· France</i></span><span class="u-board-dots"></span><span class="u-board-val">122y</span></li><li class="u-board-row"><span class="u-board-name">Kane Tanaka <i>· Japan</i></span><span class="u-board-dots"></span><span class="u-board-val">119y</span></li><li class="u-board-row"><span class="u-board-name">Sarah Knauss <i>· USA</i></span><span class="u-board-dots"></span><span class="u-board-val">119y</span></li></ol></div>',
  kpi: '<div class="u-kpis"><div class="u-kpi"><span class="u-kpi-lbl">Your age</span><span class="u-kpi-val">38</span><span class="u-kpi-sub">years</span></div><div class="u-kpi u-kpi-main"><span class="u-kpi-lbl">Likely ceiling</span><span class="u-kpi-val">~92</span><span class="u-kpi-sub">with the levers that work</span></div><div class="u-kpi"><span class="u-kpi-lbl">Years left</span><span class="u-kpi-val">~54</span><span class="u-kpi-sub">to spend well</span></div></div>',
  spec: '<dl class="u-spec"><p class="u-spec-k">Field notes · the oldest tree</p><div class="u-spec-row"><dt class="u-spec-dt">Species</dt><dd class="u-spec-dd">Great Basin bristlecone pine.</dd></div><div class="u-spec-row"><dt class="u-spec-dt">Location</dt><dd class="u-spec-dd">Withheld, to protect it.</dd></div><div class="u-spec-row"><dt class="u-spec-dt">Age</dt><dd class="u-spec-dd"><span class="u-spec-em">4,855 years</span>, by ring count.</dd></div></dl>'
};

window.LAB_SKINS = {};

window.LAB_SKINS.soft = `
.skin-soft{ --s-surface: rgba(245,241,234,0.03); --s-surface-2: var(--bg-raised); --s-hair: rgba(245,241,234,0.05); --s-divide: rgba(245,241,234,0.06); --s-gold-tint: rgba(212,196,160,0.08); --s-gold-tint-2: rgba(212,196,160,0.13); --s-gold-hair: rgba(212,196,160,0.22); --s-shadow-1: 0 1px 2px rgba(8,12,9,0.40); --s-shadow-2: 0 1px 2px rgba(8,12,9,0.40), 0 10px 30px -10px rgba(8,12,9,0.55); --s-shadow-3: 0 1px 2px rgba(8,12,9,0.40), 0 18px 44px -14px rgba(8,12,9,0.60); --s-shadow-gold: 0 1px 2px rgba(8,12,9,0.35), 0 12px 32px -12px rgba(8,12,9,0.50); color: var(--text); font-family: var(--font-body); font-size: 17px; line-height: 1.68; -webkit-font-smoothing: antialiased; padding: 32px clamp(18px,4vw,40px); max-width: 820px; margin: 0 auto; }
.skin-soft *{ box-sizing: border-box; }
.skin-soft p{ margin: 0 0 1.1em; text-wrap: pretty; } .skin-soft p:last-child{ margin-bottom:0; }
.skin-soft a{ color: var(--accent); text-decoration: none; transition: color .2s ease; } .skin-soft a:hover{ color: var(--accent-hover); }
.skin-soft strong{ color: var(--text-bright); font-weight: 600; }
.skin-soft h1,.skin-soft h2,.skin-soft h3,.skin-soft h4{ font-family: var(--font-heading); color: var(--text-bright); font-weight: 700; line-height: 1.2; margin: 0; text-wrap: balance; }
.skin-soft .u-link{ color: var(--accent); background-image: linear-gradient(var(--s-gold-hair), var(--s-gold-hair)); background-size: 100% 1px; background-position: 0 100%; background-repeat: no-repeat; padding-bottom: 1px; transition: color .2s ease, background-size .2s ease; }
.skin-soft .u-link:hover{ color: var(--accent-hover); background-size: 100% 2px; }
.skin-soft .u-hero{ background: var(--s-surface); border: 1px solid var(--s-hair); border-radius: 24px; padding: clamp(28px,5vw,46px) clamp(24px,5vw,42px); box-shadow: var(--s-shadow-2); }
.skin-soft .u-eyebrow{ display: inline-block; font-family: var(--font-mono); font-size: .72rem; letter-spacing: .16em; text-transform: uppercase; color: var(--accent); background: var(--s-gold-tint); padding: .42em .9em; border-radius: 999px; margin: 0 0 1.1em; }
.skin-soft .u-title{ font-size: clamp(2.1rem,6vw,3.2rem); letter-spacing: -0.01em; color: var(--text-bright); margin: 0 0 .5em; }
.skin-soft .u-dek{ font-size: clamp(1.08rem,2.4vw,1.32rem); line-height: 1.5; color: var(--text-dim); max-width: 46ch; margin: 0 0 1.4em; }
.skin-soft .u-meta{ font-family: var(--font-mono); font-size: .8rem; letter-spacing: .04em; color: var(--text-dim); margin: 0; } .skin-soft .u-meta .u-sep{ color: var(--accent); margin: 0 .5em; opacity:.8; }
.skin-soft .u-h2{ font-size: clamp(1.6rem,3.6vw,2.1rem); color: var(--text-bright); margin: 0; padding-left: 18px; position: relative; }
.skin-soft .u-h2::before{ content:""; position:absolute; left:0; top:.18em; bottom:.18em; width:5px; border-radius:999px; background: var(--accent); opacity:.85; }
.skin-soft .u-lead{ font-size: clamp(1.18rem,2.6vw,1.4rem); line-height: 1.6; color: var(--text); margin: 0; }
.skin-soft .u-figure{ margin: 0; } .skin-soft .u-figure-img{ display:block; width:100%; height:auto; border-radius: 20px; box-shadow: var(--s-shadow-3); background: var(--s-surface-2); }
.skin-soft .u-figure-cap{ margin: 1em 0 0; font-size: .92rem; font-style: italic; line-height: 1.5; color: var(--text-dim); text-align: center; }
.skin-soft .u-callout{ background: var(--s-gold-tint); border: 1px solid var(--s-gold-hair); border-radius: 20px; padding: clamp(22px,4vw,32px); box-shadow: var(--s-shadow-gold); }
.skin-soft .u-callout-k{ display:flex; align-items:center; gap:.6em; font-family: var(--font-mono); font-size:.74rem; letter-spacing:.14em; text-transform:uppercase; color: var(--accent); margin:0 0 .8em; }
.skin-soft .u-callout-k::before{ content:""; width:10px; height:10px; border-radius:999px; background: var(--accent); box-shadow: 0 0 0 4px var(--s-gold-tint-2); flex:none; }
.skin-soft .u-callout-body{ font-size: 1.18rem; line-height: 1.55; color: var(--text-bright); margin: 0; }
.skin-soft .u-debate{ background: var(--s-surface); border: 1px solid var(--s-hair); border-radius: 22px; padding: clamp(22px,4vw,34px); box-shadow: var(--s-shadow-2); }
.skin-soft .u-debate-q{ font-family: var(--font-heading); font-size: 1.4rem; font-weight: 700; color: var(--text-bright); margin: 0 0 1.2em; text-align: center; }
.skin-soft .u-debate-sides{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
.skin-soft .u-side{ background: var(--bg-raised); border: 1px solid var(--s-hair); border-radius: 16px; padding: 20px; box-shadow: var(--s-shadow-1); }
.skin-soft .u-side-h{ display:flex; align-items:center; gap:.5em; font-size: 1.02rem; color: var(--text-bright); margin: 0 0 .55em; }
.skin-soft .u-side-a .u-side-h::before{ content:"\\2713"; color: var(--accent); } .skin-soft .u-side-b .u-side-h::before{ content:"\\2717"; color: var(--text-dim); }
.skin-soft .u-side-p{ font-size: .98rem; line-height: 1.55; color: var(--text-dim); margin: 0; }
.skin-soft .u-take{ margin: 1.2em 0 0; padding: 14px 20px; background: var(--s-gold-tint); border-radius: 14px; font-size: 1rem; color: var(--text); text-align: center; } .skin-soft .u-take strong{ color: var(--accent); }
.skin-soft .u-checks{ list-style:none; margin:0; padding:0; display:flex; flex-direction:column; gap:12px; }
.skin-soft .u-check{ position:relative; background: var(--s-surface); border: 1px solid var(--s-hair); border-radius: 16px; padding: 16px 20px 16px 56px; font-size: 1rem; line-height: 1.5; color: var(--text-dim); box-shadow: var(--s-shadow-1); } .skin-soft .u-check strong{ color: var(--text-bright); }
.skin-soft .u-check::before{ position:absolute; left:16px; top:50%; transform:translateY(-50%); width:26px; height:26px; border-radius:999px; display:grid; place-items:center; font-size:.9rem; line-height:1; }
.skin-soft .u-check.u-use{ background: var(--s-gold-tint); border-color: var(--s-gold-hair); } .skin-soft .u-check.u-use::before{ content:"\\2713"; color: var(--bg); background: var(--accent); }
.skin-soft .u-check.u-meh::before{ content:"\\2013"; color: var(--text-bright); background: rgba(245,241,234,0.10); }
.skin-soft .u-check.u-skip{ color: var(--text-dim); } .skin-soft .u-check.u-skip::before{ content:"\\2717"; color: var(--text-dim); background: rgba(245,241,234,0.06); } .skin-soft .u-check.u-skip strong{ color: var(--text-dim); }
.skin-soft .u-stats{ display:flex; flex-wrap:wrap; gap:14px; } .skin-soft .u-stat{ flex:1 1 140px; display:flex; flex-direction:column; gap:.35em; padding:8px 4px; } .skin-soft .u-stat + .u-stat{ border-left:1px solid var(--s-divide); padding-left:22px; }
.skin-soft .u-fig{ font-family: var(--font-heading); font-size: clamp(2.2rem,5vw,2.8rem); font-weight:700; line-height:1; color: var(--accent); } .skin-soft .u-fig-lbl{ font-size:.86rem; line-height:1.4; color: var(--text-dim); }
.skin-soft .u-statcards{ display:grid; grid-template-columns: repeat(auto-fit,minmax(160px,1fr)); gap:16px; }
.skin-soft .u-statcard{ background: var(--s-surface); border: 1px solid var(--s-hair); border-radius: 18px; padding: 26px 22px; box-shadow: var(--s-shadow-2); display:flex; flex-direction:column; gap:.5em; }
.skin-soft .u-statcard-fig{ font-family: var(--font-heading); font-size: clamp(2.4rem,5vw,3rem); font-weight:700; line-height:1; color: var(--accent); } .skin-soft .u-statcard-lbl{ font-size:.9rem; line-height:1.45; color: var(--text-dim); }
.skin-soft .u-bignum{ background: var(--s-gold-tint); border: 1px solid var(--s-gold-hair); border-radius: 22px; padding: clamp(28px,5vw,42px); box-shadow: var(--s-shadow-gold); display:flex; flex-direction:column; align-items:center; text-align:center; gap:.6em; }
.skin-soft .u-bignum-fig{ font-family: var(--font-heading); font-size: clamp(4rem,14vw,7rem); font-weight:700; line-height:.9; color: var(--accent); } .skin-soft .u-bignum-u{ font-size:.42em; vertical-align:super; color: var(--accent-hover); }
.skin-soft .u-bignum-cap{ font-size: 1.08rem; line-height:1.5; color: var(--text-bright); max-width:36ch; } .skin-soft .u-bignum-src{ font-family: var(--font-mono); font-size:.74rem; letter-spacing:.1em; text-transform:uppercase; color: var(--text-dim); background: rgba(245,241,234,0.05); padding:.4em .9em; border-radius:999px; }
.skin-soft .u-strip{ display:flex; flex-wrap:wrap; gap:10px; } .skin-soft .u-strip-item{ flex:1 1 auto; background: var(--s-surface); border:1px solid var(--s-hair); border-radius:14px; padding:14px 18px; font-size:.92rem; color: var(--text-dim); box-shadow: var(--s-shadow-1); display:flex; flex-direction:column; gap:.2em; text-align:center; justify-content:center; }
.skin-soft .u-strip-item b{ font-family: var(--font-heading); font-size:1.45rem; font-weight:700; color: var(--accent); line-height:1.1; }
.skin-soft .u-pq{ position:relative; margin:0; background: var(--s-gold-tint); border-radius:22px; padding: clamp(32px,5vw,44px) clamp(26px,5vw,40px) clamp(26px,5vw,36px); box-shadow: var(--s-shadow-gold); font-family: var(--font-heading); font-size: clamp(1.5rem,4vw,2rem); line-height:1.35; font-weight:700; color: var(--text-bright); }
.skin-soft .u-pq::before{ content:"\\275D"; position:absolute; top:.12em; left:.3em; font-size:2.4em; line-height:1; color: var(--accent); opacity:.35; }
.skin-soft .u-pq-cite{ display:block; margin-top:.8em; font-family: var(--font-mono); font-size:.72rem; font-weight:400; font-style:normal; letter-spacing:.12em; text-transform:uppercase; color: var(--accent); } .skin-soft .u-pq-cite::before{ content:"\\2014 "; }
.skin-soft .u-quote{ margin:0; background: var(--s-surface); border:1px solid var(--s-hair); border-radius:20px; padding: clamp(22px,4vw,34px) clamp(22px,4vw,34px) clamp(22px,4vw,34px) clamp(38px,6vw,56px); box-shadow: var(--s-shadow-2); position:relative; }
.skin-soft .u-quote::before{ content:""; position:absolute; left: clamp(18px,3vw,26px); top: clamp(22px,4vw,34px); bottom: clamp(22px,4vw,34px); width:4px; border-radius:999px; background: var(--accent); opacity:.8; }
.skin-soft .u-quote p{ font-family: var(--font-heading); font-size:1.3rem; font-style:italic; line-height:1.5; color: var(--text); margin:0; }
.skin-soft .u-divider{ border:none; margin:8px 0; text-align:center; } .skin-soft .u-divider::before{ content:"\\00b7 \\00b7 \\00b7"; letter-spacing:.7em; font-size:1.2rem; color: var(--accent); opacity:.7; padding-left:.7em; }
.skin-soft .u-sechead{ text-align:center; display:flex; flex-direction:column; align-items:center; gap:.8em; }
.skin-soft .u-sechead-k{ font-family: var(--font-mono); font-size:.74rem; letter-spacing:.18em; text-transform:uppercase; color: var(--accent); background: var(--s-gold-tint); padding:.45em 1.1em; border-radius:999px; margin:0; }
.skin-soft .u-sechead-h{ font-size: clamp(1.8rem,4.5vw,2.5rem); color: var(--text-bright); margin:0; }
.skin-soft .u-citep{ font-size:1rem; line-height:1.6; color: var(--text); margin:0; display:flex; flex-wrap:wrap; align-items:center; gap:.5em; }
.skin-soft .u-src a{ font-family: var(--font-mono); font-size:.82rem; color: var(--accent); background: rgba(245,241,234,0.05); padding:.25em .7em; border-radius:999px; } .skin-soft .u-src a::after{ content:" \\2197"; opacity:.7; }
.skin-soft .u-grade{ font-family: var(--font-mono); font-size:.68rem; letter-spacing:.08em; text-transform:uppercase; padding:.35em .8em; border-radius:999px; } .skin-soft .u-grade-a{ color: var(--bg); background: var(--accent); } .skin-soft .u-grade-c{ color: var(--text-dim); background: rgba(245,241,234,0.06); border:1px solid var(--s-hair); }
.skin-soft .u-fnp{ font-size:1rem; line-height:1.65; color: var(--text); margin:0; } .skin-soft .u-cite{ font-size:.7em; line-height:0; vertical-align:super; margin-left:.15em; }
.skin-soft .u-cite a{ display:inline-grid; place-items:center; min-width:1.5em; height:1.5em; padding:0 .35em; border-radius:999px; background: var(--s-gold-tint); color: var(--accent); font-family: var(--font-mono); font-size:1rem; font-weight:600; } .skin-soft .u-cite a:hover{ background: var(--accent); color: var(--bg); }
.skin-soft .u-table{ width:100%; border-collapse:separate; border-spacing:0; background: var(--s-surface); border:1px solid var(--s-hair); border-radius:18px; overflow:hidden; box-shadow: var(--s-shadow-2); font-size:.98rem; }
.skin-soft .u-table thead th{ text-align:left; font-family: var(--font-mono); font-size:.72rem; font-weight:600; letter-spacing:.1em; text-transform:uppercase; color: var(--accent); background: var(--s-gold-tint); padding:16px 22px; }
.skin-soft .u-table tbody td{ padding:16px 22px; color: var(--text); border-top:1px solid var(--s-divide); } .skin-soft .u-table tbody tr:first-child td{ border-top:none; }
.skin-soft .u-table .u-num{ font-family: var(--font-mono); color: var(--text-bright); font-variant-numeric: tabular-nums; white-space:nowrap; }
.skin-soft .u-table .u-feature td{ background: var(--s-gold-tint); color: var(--text-bright); } .skin-soft .u-table .u-feature td:first-child{ font-weight:600; box-shadow: inset 4px 0 0 var(--accent); } .skin-soft .u-table .u-feature .u-num{ color: var(--accent); }
.skin-soft .u-cards{ display:grid; grid-template-columns: repeat(auto-fit,minmax(180px,1fr)); gap:16px; }
.skin-soft .u-card{ background: var(--s-surface); border:1px solid var(--s-hair); border-radius:18px; padding:26px 24px; box-shadow: var(--s-shadow-2); transition: transform .22s ease, box-shadow .22s ease; } .skin-soft .u-card:hover{ transform: translateY(-3px); box-shadow: var(--s-shadow-3); }
.skin-soft .u-card-h{ font-size:1.2rem; color: var(--text-bright); margin:0 0 .55em; } .skin-soft .u-card-p{ font-size:.96rem; line-height:1.55; color: var(--text-dim); margin:0; }
.skin-soft .u-entries{ display:flex; flex-direction:column; gap:16px; } .skin-soft .u-entry{ background: var(--s-surface); border:1px solid var(--s-hair); border-radius:18px; padding: clamp(20px,4vw,30px); box-shadow: var(--s-shadow-2); }
.skin-soft .u-entry-num{ display:inline-block; font-family: var(--font-mono); font-size:.72rem; letter-spacing:.14em; text-transform:uppercase; color: var(--accent); background: var(--s-gold-tint); padding:.4em .85em; border-radius:999px; margin:0 0 1em; }
.skin-soft .u-entry-h{ font-size: clamp(1.3rem,3vw,1.6rem); line-height:1.3; color: var(--text-bright); margin:0 0 .5em; } .skin-soft .u-entry-p{ font-size:1rem; line-height:1.6; color: var(--text-dim); margin:0; }
.skin-soft .u-steps{ list-style:none; counter-reset:step; margin:0; padding:0; display:flex; flex-direction:column; gap:14px; }
.skin-soft .u-step{ counter-increment:step; position:relative; background: var(--s-surface); border:1px solid var(--s-hair); border-radius:18px; padding:22px 24px 22px 72px; box-shadow: var(--s-shadow-1); }
.skin-soft .u-step::before{ content: counter(step); position:absolute; left:20px; top:20px; width:36px; height:36px; border-radius:999px; display:grid; place-items:center; font-family: var(--font-heading); font-size:1.1rem; font-weight:700; color: var(--accent); background: var(--s-gold-tint); border:1px solid var(--s-gold-hair); }
.skin-soft .u-step-h{ display:block; font-family: var(--font-heading); font-size:1.15rem; font-weight:700; color: var(--text-bright); margin-bottom:.35em; } .skin-soft .u-step-p{ font-size:.98rem; line-height:1.55; color: var(--text-dim); margin:0; }
.skin-soft .u-toc{ background: var(--s-surface); border:1px solid var(--s-hair); border-radius:20px; padding: clamp(20px,4vw,28px); box-shadow: var(--s-shadow-2); }
.skin-soft .u-toc-k{ font-family: var(--font-mono); font-size:.74rem; letter-spacing:.14em; text-transform:uppercase; color: var(--accent); margin:0 0 .6em; } .skin-soft .u-toc-list{ list-style:none; margin:0; padding:0; }
.skin-soft .u-toc-row{ display:flex; align-items:baseline; justify-content:space-between; gap:16px; padding:14px 16px; border-radius:12px; color: var(--text); transition: background .2s ease, color .2s ease; } .skin-soft .u-toc-row:hover{ background: var(--s-gold-tint); color: var(--text-bright); }
.skin-soft .u-toc-name{ display:flex; align-items:baseline; gap:.8em; font-size:1.05rem; } .skin-soft .u-toc-n{ font-family: var(--font-mono); font-size:.8rem; color: var(--accent); min-width:2ch; } .skin-soft .u-toc-m{ font-family: var(--font-mono); font-size:.8rem; color: var(--text-dim); white-space:nowrap; }
.skin-soft .u-collapse{ background: var(--s-surface); border:1px solid var(--s-hair); border-radius:18px; padding:6px clamp(18px,3vw,26px); box-shadow: var(--s-shadow-2); }
.skin-soft .u-collapse-s{ list-style:none; cursor:pointer; display:flex; align-items:center; gap:.7em; font-family: var(--font-heading); font-size:1.12rem; font-weight:700; color: var(--text-bright); padding:18px 0; } .skin-soft .u-collapse-s::-webkit-details-marker{ display:none; }
.skin-soft .u-collapse-s::before{ content:"\\276F"; color: var(--accent); font-size:.9em; transition: transform .25s ease; } .skin-soft .u-collapse[open] .u-collapse-s::before{ transform: rotate(90deg); }
.skin-soft .u-collapse-list{ margin:0; padding:16px 0 18px 1.4em; border-top:1px solid var(--s-divide); color: var(--text-dim); font-size:.96rem; line-height:1.65; } .skin-soft .u-collapse-list li{ margin-bottom:.7em; } .skin-soft .u-collapse-list b{ color: var(--text-bright); } .skin-soft .u-collapse-list a{ color: var(--accent); }
.skin-soft .u-dossier{ display:grid; grid-template-columns: 0.9fr 1.1fr; gap: clamp(18px,3vw,28px); background: var(--s-surface); border:1px solid var(--s-hair); border-radius:22px; padding: clamp(18px,3vw,26px); box-shadow: var(--s-shadow-3); align-items:center; }
.skin-soft .u-dossier-media{ margin:0; } .skin-soft .u-dossier-img{ display:block; width:100%; height:100%; max-height:320px; object-fit:cover; border-radius:16px; box-shadow: var(--s-shadow-1); background: var(--bg-raised); }
.skin-soft .u-dossier-cap{ margin-top:.7em; font-family: var(--font-mono); font-size:.72rem; letter-spacing:.06em; text-transform:uppercase; color: var(--text-dim); text-align:center; }
.skin-soft .u-dossier-eyebrow{ display:inline-block; font-family: var(--font-mono); font-size:.72rem; letter-spacing:.14em; text-transform:uppercase; color: var(--accent); background: var(--s-gold-tint); padding:.4em .85em; border-radius:999px; margin:0 0 .8em; }
.skin-soft .u-dossier-name{ font-size: clamp(1.6rem,4vw,2.2rem); color: var(--text-bright); margin:0 0 .5em; } .skin-soft .u-dossier-stat{ display:flex; align-items:baseline; gap:.6em; padding:14px 18px; background: var(--s-gold-tint); border-radius:14px; margin:0 0 1em; }
.skin-soft .u-dossier-fig{ font-family: var(--font-heading); font-size: clamp(1.8rem,4vw,2.4rem); font-weight:700; line-height:1; color: var(--accent); } .skin-soft .u-dossier-figlbl{ font-size:.86rem; line-height:1.35; color: var(--text-dim); } .skin-soft .u-dossier-lead{ font-size:1rem; line-height:1.6; color: var(--text); margin:0; }
.skin-soft .u-defs{ margin:0; background: var(--s-surface); border:1px solid var(--s-hair); border-radius:18px; padding: clamp(20px,3vw,30px); box-shadow: var(--s-shadow-2); }
.skin-soft .u-defs-t{ font-family: var(--font-heading); font-size:1.12rem; font-weight:700; color: var(--text-bright); display:flex; align-items:center; gap:.55em; } .skin-soft .u-defs-t::before{ content:""; width:8px; height:8px; border-radius:999px; background: var(--accent); flex:none; }
.skin-soft .u-defs-d{ margin:.35em 0 0 1.3em; font-size:1rem; line-height:1.55; color: var(--text-dim); } .skin-soft .u-defs-d + .u-defs-t{ margin-top:1.3em; padding-top:1.3em; border-top:1px solid var(--s-divide); }
.skin-soft .u-board{ background: var(--s-surface); border:1px solid var(--s-hair); border-radius:20px; padding: clamp(20px,4vw,28px); box-shadow: var(--s-shadow-2); } .skin-soft .u-board-k{ font-family: var(--font-mono); font-size:.74rem; letter-spacing:.14em; text-transform:uppercase; color: var(--accent); margin:0 0 1em; }
.skin-soft .u-board-list{ list-style:none; counter-reset:rank; margin:0; padding:0; } .skin-soft .u-board-row{ counter-increment:rank; display:flex; align-items:center; gap:14px; padding:14px 16px; border-radius:14px; } .skin-soft .u-board-row:nth-child(odd){ background: rgba(245,241,234,0.03); }
.skin-soft .u-board-row::before{ content: counter(rank); flex:none; width:30px; height:30px; border-radius:999px; display:grid; place-items:center; font-family: var(--font-mono); font-size:.85rem; font-weight:600; color: var(--text-dim); background: rgba(245,241,234,0.05); } .skin-soft .u-board-row:first-child::before{ color: var(--bg); background: var(--accent); }
.skin-soft .u-board-name{ font-size:1.02rem; color: var(--text-bright); } .skin-soft .u-board-name i{ font-style:normal; color: var(--text-dim); font-size:.9em; }
.skin-soft .u-board-dots{ flex:1 1 auto; height:1px; min-width:12px; margin-bottom:4px; background-image: radial-gradient(currentColor 1px, transparent 1.4px); background-size:7px 2px; background-repeat: repeat-x; background-position:0 100%; color: var(--rule); opacity:.8; }
.skin-soft .u-board-val{ font-family: var(--font-mono); font-size:1.02rem; font-weight:600; color: var(--accent); font-variant-numeric: tabular-nums; white-space:nowrap; }
.skin-soft .u-kpis{ display:grid; grid-template-columns: repeat(auto-fit,minmax(150px,1fr)); gap:16px; } .skin-soft .u-kpi{ background: var(--s-surface); border:1px solid var(--s-hair); border-radius:18px; padding:24px 22px; box-shadow: var(--s-shadow-2); display:flex; flex-direction:column; gap:.3em; }
.skin-soft .u-kpi-lbl{ font-family: var(--font-mono); font-size:.72rem; letter-spacing:.1em; text-transform:uppercase; color: var(--text-dim); } .skin-soft .u-kpi-val{ font-family: var(--font-heading); font-size: clamp(2.2rem,5vw,2.8rem); font-weight:700; line-height:1; color: var(--text-bright); margin:.1em 0; } .skin-soft .u-kpi-sub{ font-size:.86rem; line-height:1.4; color: var(--text-dim); }
.skin-soft .u-kpi.u-kpi-main{ background: var(--s-gold-tint); border-color: var(--s-gold-hair); box-shadow: var(--s-shadow-gold); } .skin-soft .u-kpi.u-kpi-main .u-kpi-lbl{ color: var(--accent); } .skin-soft .u-kpi.u-kpi-main .u-kpi-val{ color: var(--accent); }
.skin-soft .u-spec{ margin:0; background: var(--s-surface); border:1px solid var(--s-hair); border-radius:20px; padding: clamp(8px,2vw,14px) clamp(22px,4vw,30px) clamp(18px,3vw,26px); box-shadow: var(--s-shadow-2); }
.skin-soft .u-spec-k{ font-family: var(--font-mono); font-size:.74rem; letter-spacing:.14em; text-transform:uppercase; color: var(--accent); margin:0; padding:18px 0 14px; } .skin-soft .u-spec-row{ display:grid; grid-template-columns:130px 1fr; gap:16px; padding:14px 0; border-top:1px solid var(--s-divide); align-items:baseline; }
.skin-soft .u-spec-dt{ font-family: var(--font-mono); font-size:.82rem; letter-spacing:.04em; text-transform:uppercase; color: var(--text-dim); margin:0; } .skin-soft .u-spec-dd{ margin:0; font-size:1rem; line-height:1.55; color: var(--text); } .skin-soft .u-spec-em{ color: var(--accent); font-weight:600; }
`;

window.LAB_SKINS.sharp = `
.skin-sharp{ font-family: var(--font-body); color: var(--text); font-size:16px; line-height:1.6; -webkit-font-smoothing: antialiased; padding: 30px clamp(18px,4vw,40px); max-width: 820px; margin:0 auto; }
.skin-sharp *,.skin-sharp *::before,.skin-sharp *::after{ box-sizing:border-box; } .skin-sharp p{ margin:0; }
.skin-sharp .u-link{ color: var(--accent); text-decoration:none; border-bottom:1px solid rgba(212,196,160,0.32); transition: color .14s ease, border-color .14s ease; } .skin-sharp .u-link:hover{ color: var(--accent-hover); border-bottom-color: rgba(237,224,192,0.7); }
.skin-sharp strong,.skin-sharp b{ color: var(--text-bright); font-weight:600; }
.skin-sharp .u-eyebrow,.skin-sharp .u-callout-k,.skin-sharp .u-sechead-k,.skin-sharp .u-toc-k,.skin-sharp .u-board-k,.skin-sharp .u-dossier-eyebrow,.skin-sharp .u-spec-k{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.16em; font-size:.7rem; font-weight:400; color: var(--text-dim); margin:0; }
.skin-sharp .u-hero{ position:relative; padding:30px 0 26px; } .skin-sharp .u-hero .u-eyebrow{ color: var(--accent); display:inline-flex; align-items:center; margin-bottom:18px; } .skin-sharp .u-hero .u-eyebrow::before{ content:""; display:inline-block; width:18px; height:1px; background: var(--accent); margin-right:10px; opacity:.7; }
.skin-sharp .u-title{ font-family: var(--font-heading); font-weight:700; font-size: clamp(2.4rem,5.5vw,3.6rem); line-height:1.04; letter-spacing:-0.02em; color: var(--text-bright); margin:0 0 .5em; }
.skin-sharp .u-dek{ font-size:1.18rem; line-height:1.5; color: var(--text-dim); max-width:620px; margin:0 0 1.4em; } .skin-sharp .u-meta{ font-family: var(--font-mono); font-size:.74rem; letter-spacing:.08em; text-transform:uppercase; color: var(--text-dim); font-variant-numeric: tabular-nums; padding-top:16px; border-top:1px solid rgba(245,241,234,0.08); display:inline-block; } .skin-sharp .u-meta .u-sep{ color: var(--rule); margin:0 .5em; }
.skin-sharp .u-h2{ font-family: var(--font-heading); font-weight:700; font-size:1.9rem; letter-spacing:-0.015em; line-height:1.18; color: var(--text-bright); margin:0; padding-left:14px; border-left:2px solid var(--accent); }
.skin-sharp .u-lead{ font-size:1.24rem; line-height:1.55; color: var(--text-bright); max-width:680px; margin:0; } .skin-sharp .u-lead strong{ color: var(--accent-hover); }
.skin-sharp .u-figure{ margin:0; } .skin-sharp .u-figure-img{ display:block; width:100%; height:auto; border-radius:10px; border:1px solid rgba(245,241,234,0.08); box-shadow: inset 0 1px 0 rgba(245,241,234,0.05), 0 6px 24px rgba(0,0,0,0.28); }
.skin-sharp .u-figure-cap{ font-family: var(--font-mono); font-size:.72rem; letter-spacing:.05em; color: var(--text-dim); margin-top:12px; padding-left:12px; border-left:1px solid var(--rule); line-height:1.5; }
.skin-sharp .u-callout{ position:relative; background: var(--bg-raised); border:1px solid rgba(245,241,234,0.08); border-left:2px solid var(--accent); border-radius:8px; padding:20px 24px 22px; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); } .skin-sharp .u-callout-k{ color: var(--accent); margin-bottom:10px; } .skin-sharp .u-callout-body{ font-size:1.08rem; line-height:1.5; color: var(--text-bright); margin:0; }
.skin-sharp .u-debate{ border:1px solid rgba(245,241,234,0.08); border-radius:10px; background: var(--bg-raised); padding:22px 24px 24px; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); }
.skin-sharp .u-debate-q{ font-family: var(--font-heading); font-size:1.35rem; font-weight:700; letter-spacing:-0.015em; color: var(--text-bright); margin:0 0 18px; }
.skin-sharp .u-debate-sides{ display:grid; grid-template-columns:1fr 1fr; gap:1px; background: rgba(245,241,234,0.08); border:1px solid rgba(245,241,234,0.08); border-radius:8px; overflow:hidden; } .skin-sharp .u-side{ background: var(--bg); padding:16px 18px; }
.skin-sharp .u-side-h{ font-family: var(--font-mono); font-size:.72rem; text-transform:uppercase; letter-spacing:.12em; margin:0 0 8px; display:flex; align-items:center; gap:8px; } .skin-sharp .u-side-a .u-side-h{ color: var(--accent); } .skin-sharp .u-side-b .u-side-h{ color: var(--text-dim); } .skin-sharp .u-side-a .u-side-h::before{ content:"\\2713"; } .skin-sharp .u-side-b .u-side-h::before{ content:"\\2717"; opacity:.7; }
.skin-sharp .u-side-p{ font-size:.95rem; line-height:1.5; color: var(--text); margin:0; } .skin-sharp .u-take{ font-size:.98rem; color: var(--text-dim); margin:16px 0 0; padding-top:14px; border-top:1px solid rgba(245,241,234,0.08); } .skin-sharp .u-take strong{ color: var(--accent); }
.skin-sharp .u-checks{ list-style:none; margin:0; padding:0; border:1px solid rgba(245,241,234,0.08); border-radius:10px; background: var(--bg-raised); overflow:hidden; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); }
.skin-sharp .u-check{ position:relative; font-size:1rem; line-height:1.5; color: var(--text); padding:14px 18px 14px 46px; border-bottom:1px solid rgba(245,241,234,0.08); } .skin-sharp .u-check:last-child{ border-bottom:0; }
.skin-sharp .u-check::before{ position:absolute; left:18px; top:14px; font-family: var(--font-mono); font-size:.95rem; line-height:1.5; font-weight:700; width:16px; text-align:center; } .skin-sharp .u-check.u-use::before{ content:"\\2713"; color: var(--accent); } .skin-sharp .u-check.u-meh::before{ content:"\\00b7"; color: var(--text-dim); } .skin-sharp .u-check.u-skip::before{ content:"\\2717"; color: var(--text-dim); opacity:.6; } .skin-sharp .u-check.u-skip{ color: var(--text-dim); }
.skin-sharp .u-stats{ display:flex; flex-wrap:wrap; gap:36px; padding:4px 0; } .skin-sharp .u-stat{ display:flex; flex-direction:column; gap:6px; min-width:130px; flex:1; } .skin-sharp .u-fig{ font-family: var(--font-mono); font-size:2.4rem; font-weight:700; line-height:1; letter-spacing:-0.02em; color: var(--accent); font-variant-numeric: tabular-nums; } .skin-sharp .u-fig-lbl{ font-size:.82rem; line-height:1.4; color: var(--text-dim); }
.skin-sharp .u-statcards{ display:grid; grid-template-columns: repeat(auto-fit,minmax(180px,1fr)); gap:12px; } .skin-sharp .u-statcard{ position:relative; background: var(--bg-raised); border:1px solid rgba(245,241,234,0.08); border-radius:8px; padding:18px 20px; display:flex; flex-direction:column; gap:8px; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); transition: border-color .14s ease; } .skin-sharp .u-statcard:hover{ border-color: rgba(245,241,234,0.14); }
.skin-sharp .u-statcard-fig{ font-family: var(--font-mono); font-size:2.2rem; font-weight:700; line-height:1; letter-spacing:-0.02em; color: var(--accent); font-variant-numeric: tabular-nums; } .skin-sharp .u-statcard-lbl{ font-size:.82rem; line-height:1.4; color: var(--text-dim); }
.skin-sharp .u-bignum{ position:relative; padding:26px 28px; background: var(--bg-raised); border:1px solid rgba(245,241,234,0.08); border-radius:10px; display:grid; grid-template-columns:auto 1fr; grid-template-rows:auto auto; column-gap:26px; align-items:center; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); }
.skin-sharp .u-bignum-fig{ grid-row:1 / 3; font-family: var(--font-mono); font-size: clamp(3.4rem,8vw,5rem); font-weight:700; line-height:.9; letter-spacing:-0.03em; color: var(--accent); font-variant-numeric: tabular-nums; } .skin-sharp .u-bignum-u{ font-size:.5em; vertical-align:super; color: var(--text-dim); margin-left:2px; }
.skin-sharp .u-bignum-cap{ align-self:flex-end; font-size:1.02rem; line-height:1.45; color: var(--text-bright); } .skin-sharp .u-bignum-src{ align-self:flex-start; font-family: var(--font-mono); font-size:.7rem; text-transform:uppercase; letter-spacing:.1em; color: var(--text-dim); margin-top:10px; padding-top:10px; border-top:1px solid rgba(245,241,234,0.08); }
.skin-sharp .u-strip{ display:flex; flex-wrap:wrap; align-items:stretch; border:1px solid rgba(245,241,234,0.08); border-radius:8px; background: var(--bg-raised); overflow:hidden; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); }
.skin-sharp .u-strip-item{ flex:1; min-width:140px; padding:14px 18px; font-size:.84rem; line-height:1.4; color: var(--text-dim); border-left:1px solid rgba(245,241,234,0.08); } .skin-sharp .u-strip-item:first-child{ border-left:0; } .skin-sharp .u-strip-item b{ display:block; font-family: var(--font-mono); font-size:1.5rem; font-weight:700; letter-spacing:-0.01em; color: var(--accent); font-variant-numeric: tabular-nums; margin-bottom:3px; }
.skin-sharp .u-pq{ margin:0; padding:4px 0 4px 22px; border-left:2px solid var(--accent); font-family: var(--font-heading); font-size:1.55rem; line-height:1.32; letter-spacing:-0.01em; font-style:italic; color: var(--text-bright); } .skin-sharp .u-pq-cite{ display:block; margin-top:14px; font-family: var(--font-mono); font-style:normal; font-size:.7rem; text-transform:uppercase; letter-spacing:.12em; color: var(--text-dim); } .skin-sharp .u-pq-cite::before{ content:"\\2014 "; color: var(--accent); }
.skin-sharp .u-quote{ margin:0; padding:18px 24px; background: var(--bg-raised); border:1px solid rgba(245,241,234,0.08); border-left:2px solid var(--accent); border-radius:8px; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); } .skin-sharp .u-quote p{ margin:0; font-family: var(--font-heading); font-size:1.22rem; line-height:1.45; color: var(--text-bright); }
.skin-sharp .u-divider{ border:0; height:1px; margin:8px 0; background: linear-gradient(90deg, transparent 0%, rgba(245,241,234,0.08) 12%, rgba(245,241,234,0.08) 44%, rgba(212,196,160,0.5) 50%, rgba(245,241,234,0.08) 56%, rgba(245,241,234,0.08) 88%, transparent 100%); }
.skin-sharp .u-sechead{ padding-bottom:14px; border-bottom:1px solid rgba(245,241,234,0.08); } .skin-sharp .u-sechead-k{ color: var(--accent); margin-bottom:10px; display:inline-flex; align-items:center; } .skin-sharp .u-sechead-k::before{ content:""; display:inline-block; width:16px; height:1px; background: var(--accent); margin-right:10px; opacity:.7; }
.skin-sharp .u-sechead-h{ font-family: var(--font-heading); font-weight:700; font-size:2rem; letter-spacing:-0.018em; line-height:1.12; color: var(--text-bright); margin:0; }
.skin-sharp .u-citep{ font-size:1rem; line-height:1.6; color: var(--text); margin:0; } .skin-sharp .u-src{ font-family: var(--font-mono); font-size:.78rem; } .skin-sharp .u-src a{ color: var(--accent); border-bottom:1px solid rgba(212,196,160,0.32); }
.skin-sharp .u-grade{ display:inline-block; font-family: var(--font-mono); font-size:.64rem; text-transform:uppercase; letter-spacing:.1em; font-weight:700; padding:2px 8px; border-radius:999px; border:1px solid rgba(245,241,234,0.14); vertical-align:middle; margin-left:6px; line-height:1.4; } .skin-sharp .u-grade-a{ color: var(--accent); border-color: rgba(212,196,160,0.5); background: rgba(212,196,160,0.12); } .skin-sharp .u-grade-a::before{ content:"\\2713 "; } .skin-sharp .u-grade-c{ color: var(--text-dim); } .skin-sharp .u-grade-c::before{ content:"\\00b7 "; }
.skin-sharp .u-fnp{ font-size:1rem; line-height:1.65; color: var(--text); margin:0; } .skin-sharp .u-cite{ font-size:.7em; line-height:0; } .skin-sharp .u-cite a{ font-family: var(--font-mono); color: var(--accent); font-variant-numeric: tabular-nums; padding:0 2px; border-bottom:1px solid rgba(212,196,160,0.4); }
.skin-sharp .u-table{ width:100%; border-collapse:separate; border-spacing:0; font-size:.95rem; border:1px solid rgba(245,241,234,0.08); border-radius:10px; overflow:hidden; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); }
.skin-sharp .u-table thead th{ font-family: var(--font-mono); font-size:.68rem; text-transform:uppercase; letter-spacing:.12em; font-weight:400; text-align:left; color: var(--text-dim); background: var(--bg-raised); padding:11px 16px; border-bottom:1px solid rgba(245,241,234,0.14); }
.skin-sharp .u-table tbody td{ padding:12px 16px; color: var(--text); border-bottom:1px solid rgba(245,241,234,0.08); line-height:1.4; } .skin-sharp .u-table tbody tr:last-child td{ border-bottom:0; } .skin-sharp .u-table .u-num{ font-family: var(--font-mono); font-variant-numeric: tabular-nums; color: var(--text-bright); text-align:right; white-space:nowrap; }
.skin-sharp .u-table tbody tr.u-feature td{ background: rgba(212,196,160,0.12); color: var(--text-bright); } .skin-sharp .u-table tbody tr.u-feature td:first-child{ box-shadow: inset 2px 0 0 var(--accent); font-weight:600; } .skin-sharp .u-table tbody tr.u-feature .u-num{ color: var(--accent); }
.skin-sharp .u-cards{ display:grid; grid-template-columns: repeat(auto-fit,minmax(190px,1fr)); gap:12px; } .skin-sharp .u-card{ position:relative; background: var(--bg-raised); border:1px solid rgba(245,241,234,0.08); border-radius:8px; padding:18px 20px 20px; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); transition: border-color .14s ease, transform .14s ease; } .skin-sharp .u-card:hover{ border-color: rgba(245,241,234,0.14); transform: translateY(-1px); }
.skin-sharp .u-card-h{ font-family: var(--font-heading); font-size:1.18rem; font-weight:700; letter-spacing:-0.01em; color: var(--text-bright); margin:0 0 8px; } .skin-sharp .u-card-p{ font-size:.92rem; line-height:1.5; color: var(--text-dim); margin:0; }
.skin-sharp .u-entries{ display:flex; flex-direction:column; border-top:1px solid rgba(245,241,234,0.08); } .skin-sharp .u-entry{ display:grid; grid-template-columns:auto 1fr; column-gap:22px; align-items:baseline; padding:20px 4px; border-bottom:1px solid rgba(245,241,234,0.08); }
.skin-sharp .u-entry-num{ font-family: var(--font-mono); font-size:.74rem; letter-spacing:.08em; text-transform:uppercase; color: var(--accent); font-variant-numeric: tabular-nums; white-space:nowrap; padding-top:4px; } .skin-sharp .u-entry-h{ font-family: var(--font-heading); font-size:1.3rem; font-weight:700; letter-spacing:-0.015em; line-height:1.22; color: var(--text-bright); margin:0 0 6px; } .skin-sharp .u-entry-p{ grid-column:2; font-size:.95rem; line-height:1.5; color: var(--text-dim); margin:0; }
.skin-sharp .u-steps{ list-style:none; counter-reset:u-step; margin:0; padding:0; } .skin-sharp .u-step{ counter-increment:u-step; position:relative; padding:0 0 22px 52px; } .skin-sharp .u-step:last-child{ padding-bottom:0; }
.skin-sharp .u-step::before{ content: counter(u-step, decimal-leading-zero); position:absolute; left:0; top:0; width:32px; height:32px; display:flex; align-items:center; justify-content:center; font-family: var(--font-mono); font-size:.8rem; font-weight:700; color: var(--accent); font-variant-numeric: tabular-nums; background: var(--bg-raised); border:1px solid rgba(212,196,160,0.5); border-radius:8px; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); }
.skin-sharp .u-step::after{ content:""; position:absolute; left:16px; top:36px; bottom:8px; width:1px; background: rgba(245,241,234,0.08); } .skin-sharp .u-step:last-child::after{ display:none; } .skin-sharp .u-step-h{ display:block; font-family: var(--font-heading); font-size:1.12rem; font-weight:700; letter-spacing:-0.01em; color: var(--text-bright); margin-bottom:4px; padding-top:5px; } .skin-sharp .u-step-p{ font-size:.95rem; line-height:1.5; color: var(--text-dim); margin:0; }
.skin-sharp .u-toc{ background: var(--bg-raised); border:1px solid rgba(245,241,234,0.08); border-radius:10px; padding:18px 8px 10px; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); } .skin-sharp .u-toc-k{ color: var(--text-dim); padding:0 14px; margin-bottom:8px; } .skin-sharp .u-toc-list{ list-style:none; margin:0; padding:0; }
.skin-sharp .u-toc-row{ display:flex; align-items:center; justify-content:space-between; gap:14px; padding:11px 14px; border-radius:6px; color: var(--text); text-decoration:none; transition: background .14s ease, color .14s ease; } .skin-sharp .u-toc-row:hover{ background: rgba(245,241,234,0.05); color: var(--text-bright); }
.skin-sharp .u-toc-name{ display:flex; align-items:baseline; gap:12px; font-size:.98rem; } .skin-sharp .u-toc-n{ font-family: var(--font-mono); font-size:.74rem; color: var(--accent); font-variant-numeric: tabular-nums; } .skin-sharp .u-toc-m{ font-family: var(--font-mono); font-size:.72rem; color: var(--text-dim); font-variant-numeric: tabular-nums; white-space:nowrap; }
.skin-sharp .u-collapse{ background: var(--bg-raised); border:1px solid rgba(245,241,234,0.08); border-radius:10px; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); overflow:hidden; } .skin-sharp .u-collapse-s{ list-style:none; cursor:pointer; font-family: var(--font-mono); font-size:.74rem; text-transform:uppercase; letter-spacing:.1em; color: var(--text-bright); padding:14px 18px; display:flex; align-items:center; gap:12px; transition: background .14s ease; } .skin-sharp .u-collapse-s:hover{ background: rgba(245,241,234,0.05); } .skin-sharp .u-collapse-s::-webkit-details-marker{ display:none; }
.skin-sharp .u-collapse-s::before{ content:"+"; font-size:1rem; color: var(--accent); width:12px; text-align:center; } .skin-sharp .u-collapse[open] .u-collapse-s::before{ content:"\\2013"; } .skin-sharp .u-collapse[open] .u-collapse-s{ border-bottom:1px solid rgba(245,241,234,0.08); }
.skin-sharp .u-collapse-list{ margin:0; padding:12px 18px 16px 38px; font-size:.9rem; line-height:1.6; color: var(--text-dim); } .skin-sharp .u-collapse-list li{ margin-bottom:8px; } .skin-sharp .u-collapse-list b{ color: var(--text); } .skin-sharp .u-collapse-list a{ color: var(--accent); border-bottom:1px solid rgba(212,196,160,0.32); }
.skin-sharp .u-dossier{ display:grid; grid-template-columns:220px 1fr; gap:1px; background: rgba(245,241,234,0.08); border:1px solid rgba(245,241,234,0.08); border-radius:10px; overflow:hidden; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); } .skin-sharp .u-dossier-media{ margin:0; background: var(--bg); display:flex; flex-direction:column; } .skin-sharp .u-dossier-img{ display:block; width:100%; height:100%; min-height:180px; object-fit:cover; } .skin-sharp .u-dossier-cap{ font-family: var(--font-mono); font-size:.68rem; text-transform:uppercase; letter-spacing:.08em; color: var(--text-dim); padding:10px 14px; border-top:1px solid rgba(245,241,234,0.08); }
.skin-sharp .u-dossier-body{ background: var(--bg-raised); padding:22px 24px; } .skin-sharp .u-dossier-eyebrow{ color: var(--accent); margin-bottom:6px; } .skin-sharp .u-dossier-name{ font-family: var(--font-heading); font-size:1.6rem; font-weight:700; letter-spacing:-0.018em; color: var(--text-bright); margin:0 0 14px; line-height:1.1; }
.skin-sharp .u-dossier-stat{ display:flex; align-items:baseline; gap:10px; padding:12px 0; margin-bottom:12px; border-top:1px solid rgba(245,241,234,0.08); border-bottom:1px solid rgba(245,241,234,0.08); } .skin-sharp .u-dossier-fig{ font-family: var(--font-mono); font-size:1.9rem; font-weight:700; letter-spacing:-0.02em; color: var(--accent); font-variant-numeric: tabular-nums; line-height:1; } .skin-sharp .u-dossier-figlbl{ font-size:.8rem; color: var(--text-dim); line-height:1.3; } .skin-sharp .u-dossier-lead{ font-size:.98rem; line-height:1.5; color: var(--text); margin:0; }
.skin-sharp .u-defs{ margin:0; border-top:1px solid rgba(245,241,234,0.08); } .skin-sharp .u-defs-t{ font-family: var(--font-mono); font-size:.78rem; text-transform:uppercase; letter-spacing:.1em; color: var(--accent); padding-top:16px; margin:0; } .skin-sharp .u-defs-d{ font-size:1rem; line-height:1.5; color: var(--text); margin:6px 0 16px; padding-bottom:16px; border-bottom:1px solid rgba(245,241,234,0.08); }
.skin-sharp .u-board{ background: var(--bg-raised); border:1px solid rgba(245,241,234,0.08); border-radius:10px; padding:18px 8px 12px; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); } .skin-sharp .u-board-k{ color: var(--text-dim); padding:0 14px; margin-bottom:8px; } .skin-sharp .u-board-list{ list-style:none; counter-reset:u-board; margin:0; padding:0; }
.skin-sharp .u-board-row{ counter-increment:u-board; display:flex; align-items:baseline; gap:12px; padding:10px 14px; border-radius:6px; } .skin-sharp .u-board-row::before{ content: counter(u-board); font-family: var(--font-mono); font-size:.74rem; font-weight:700; color: var(--accent); font-variant-numeric: tabular-nums; width:16px; text-align:right; flex:none; } .skin-sharp .u-board-name{ font-size:.98rem; color: var(--text-bright); white-space:nowrap; } .skin-sharp .u-board-name i{ font-style:normal; color: var(--text-dim); font-size:.86rem; }
.skin-sharp .u-board-dots{ flex:1; align-self:center; height:1px; margin:0 4px; background-image: linear-gradient(90deg, var(--rule) 33%, transparent 0); background-size:5px 1px; background-repeat: repeat-x; opacity:.7; } .skin-sharp .u-board-val{ font-family: var(--font-mono); font-size:.95rem; font-weight:700; color: var(--accent); font-variant-numeric: tabular-nums; white-space:nowrap; }
.skin-sharp .u-kpis{ display:grid; grid-template-columns: repeat(auto-fit,minmax(160px,1fr)); gap:12px; } .skin-sharp .u-kpi{ position:relative; background: var(--bg-raised); border:1px solid rgba(245,241,234,0.08); border-radius:8px; padding:16px 18px 18px; display:flex; flex-direction:column; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); }
.skin-sharp .u-kpi-lbl{ font-family: var(--font-mono); font-size:.66rem; text-transform:uppercase; letter-spacing:.12em; color: var(--text-dim); margin-bottom:10px; } .skin-sharp .u-kpi-val{ font-family: var(--font-mono); font-size:2.1rem; font-weight:700; line-height:1; letter-spacing:-0.02em; color: var(--text-bright); font-variant-numeric: tabular-nums; margin-bottom:6px; } .skin-sharp .u-kpi-sub{ font-size:.78rem; line-height:1.35; color: var(--text-dim); }
.skin-sharp .u-kpi-main{ border-color: rgba(212,196,160,0.5); background: linear-gradient(0deg, rgba(212,196,160,0.12), rgba(212,196,160,0.12)), var(--bg-raised); box-shadow: inset 0 1px 0 rgba(245,241,234,0.05), 0 0 0 1px rgba(212,196,160,0.5), 0 2px 12px rgba(212,196,160,0.12); } .skin-sharp .u-kpi-main .u-kpi-lbl{ color: var(--accent); } .skin-sharp .u-kpi-main .u-kpi-val{ color: var(--accent-hover); }
.skin-sharp .u-spec{ margin:0; background: var(--bg-raised); border:1px solid rgba(245,241,234,0.08); border-radius:10px; overflow:hidden; box-shadow: inset 0 1px 0 rgba(245,241,234,0.05); } .skin-sharp .u-spec-k{ color: var(--text-dim); padding:13px 18px; background: var(--bg); border-bottom:1px solid rgba(245,241,234,0.08); margin:0; }
.skin-sharp .u-spec-row{ display:grid; grid-template-columns:130px 1fr; gap:16px; padding:12px 18px; border-bottom:1px solid rgba(245,241,234,0.08); } .skin-sharp .u-spec-row:last-child{ border-bottom:0; } .skin-sharp .u-spec-dt{ font-family: var(--font-mono); font-size:.72rem; text-transform:uppercase; letter-spacing:.08em; color: var(--accent); padding-top:2px; } .skin-sharp .u-spec-dd{ font-size:.96rem; line-height:1.45; color: var(--text); margin:0; } .skin-sharp .u-spec-em{ font-family: var(--font-mono); color: var(--text-bright); font-variant-numeric: tabular-nums; font-weight:700; }
@media (max-width:560px){ .skin-sharp .u-debate-sides{ grid-template-columns:1fr; } .skin-sharp .u-dossier{ grid-template-columns:1fr; } .skin-sharp .u-spec-row{ grid-template-columns:1fr; gap:4px; } .skin-sharp .u-bignum{ grid-template-columns:1fr; } .skin-sharp .u-bignum-fig{ grid-row:auto; } .skin-sharp .u-entry{ grid-template-columns:1fr; row-gap:6px; } .skin-sharp .u-entry-p{ grid-column:1; } }
`;

window.LAB_SKINS.editorial = `
.skin-editorial{ color: var(--text); font-family: var(--font-heading); font-size:19px; line-height:1.62; font-weight:400; -webkit-font-smoothing: antialiased; padding: 34px clamp(20px,5vw,52px); max-width: 760px; margin:0 auto; }
.skin-editorial *{ box-sizing:border-box; } .skin-editorial p{ margin:0 0 1.15em; } .skin-editorial p:last-child{ margin-bottom:0; } .skin-editorial strong{ font-weight:600; color: var(--text-bright); } .skin-editorial em{ font-style:italic; }
.skin-editorial a{ color: var(--accent); text-decoration: underline; text-decoration-thickness:1px; text-decoration-color: rgba(212,196,160,0.45); text-underline-offset:3px; transition: color .15s ease, text-decoration-color .15s ease; } .skin-editorial a:hover{ color: var(--accent-hover); text-decoration-color: var(--accent-hover); }
.skin-editorial .u-eyebrow,.skin-editorial .u-callout-k,.skin-editorial .u-sechead-k,.skin-editorial .u-toc-k,.skin-editorial .u-board-k,.skin-editorial .u-dossier-eyebrow,.skin-editorial .u-spec-k{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.18em; font-size:11.5px; font-weight:500; color: var(--accent); }
.skin-editorial .u-hero{ padding:.5rem 0 1.75rem; border-bottom:1px solid var(--rule); } .skin-editorial .u-eyebrow{ margin:0 0 1.4rem; } .skin-editorial .u-title{ font-family: var(--font-heading); font-weight:400; font-size: clamp(2.7rem,6vw,4.1rem); line-height:1.04; letter-spacing:-0.012em; color: var(--text-bright); margin:0 0 1.1rem; }
.skin-editorial .u-dek{ font-family: var(--font-heading); font-style:italic; font-size: clamp(1.18rem,2.4vw,1.42rem); line-height:1.5; color: var(--text-dim); max-width:38rem; margin:0 0 1.5rem; } .skin-editorial .u-meta{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.14em; font-size:11.5px; color: var(--text-dim); margin:0; } .skin-editorial .u-meta .u-sep{ color: var(--accent); margin:0 .5em; }
.skin-editorial .u-h2{ font-family: var(--font-heading); font-weight:400; font-size: clamp(1.9rem,4vw,2.5rem); line-height:1.12; letter-spacing:-0.01em; color: var(--text-bright); margin:0; padding-bottom:.55rem; border-bottom:1px solid var(--rule); }
.skin-editorial .u-lead{ font-family: var(--font-heading); font-size: clamp(1.2rem,2.6vw,1.42rem); line-height:1.6; color: var(--text); margin:0; } .skin-editorial .u-lead::first-letter{ float:left; font-family: var(--font-heading); font-weight:400; color: var(--accent); font-size:4.6em; line-height:0.78; padding:.06em .12em 0 0; margin:.02em 0 -.06em; } .skin-editorial .u-lead strong{ color: var(--accent); font-weight:600; }
.skin-editorial .u-figure{ margin:0; } .skin-editorial .u-figure-img{ display:block; width:100%; height:auto; border-radius:2px; border:1px solid var(--rule); box-shadow: 0 18px 40px -18px rgba(8,12,9,0.5); } .skin-editorial .u-figure-cap{ font-family: var(--font-heading); font-style:italic; font-size:.92rem; color: var(--text-dim); margin-top:.8rem; padding-left:1rem; border-left:1px solid var(--accent); }
.skin-editorial .u-callout{ padding:.3rem 0 .3rem 1.6rem; border-left:2px solid var(--accent); } .skin-editorial .u-callout-k{ margin:0 0 .55rem; } .skin-editorial .u-callout-body{ font-family: var(--font-heading); font-size:1.3rem; font-style:italic; line-height:1.5; color: var(--text-bright); margin:0; }
.skin-editorial .u-debate{ border-top:1px solid var(--rule); border-bottom:1px solid var(--rule); padding:1.4rem 0; } .skin-editorial .u-debate-q{ font-family: var(--font-heading); font-style:italic; font-size:1.5rem; line-height:1.3; color: var(--text-bright); text-align:center; margin:0 0 1.5rem; }
.skin-editorial .u-debate-sides{ display:grid; grid-template-columns:1fr 1fr; gap:2.2rem; position:relative; } .skin-editorial .u-debate-sides::before{ content:""; position:absolute; top:0; bottom:0; left:50%; width:1px; background: var(--rule); }
.skin-editorial .u-side-h{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.14em; font-size:12px; font-weight:600; margin:0 0 .6rem; padding-bottom:.4rem; border-bottom:1px solid rgba(212,196,160,0.25); } .skin-editorial .u-side-a .u-side-h{ color: var(--accent); } .skin-editorial .u-side-b .u-side-h{ color: var(--text-dim); } .skin-editorial .u-side-p{ font-family: var(--font-heading); font-size:1.02rem; line-height:1.5; color: var(--text); margin:0; }
.skin-editorial .u-take{ text-align:center; font-family: var(--font-heading); font-style:italic; color: var(--text-dim); margin:1.5rem 0 0; padding-top:1.1rem; border-top:1px solid var(--rule); } .skin-editorial .u-take strong{ font-family: var(--font-mono); font-style:normal; text-transform:uppercase; letter-spacing:.12em; font-size:11.5px; color: var(--accent); font-weight:600; }
.skin-editorial .u-checks{ list-style:none; margin:0; padding:0; border-top:1px solid var(--rule); } .skin-editorial .u-check{ position:relative; padding:.85rem 0 .85rem 2.4rem; border-bottom:1px solid var(--rule); font-family: var(--font-heading); font-size:1.05rem; line-height:1.5; color: var(--text); } .skin-editorial .u-check strong{ color: var(--text-bright); }
.skin-editorial .u-check::before{ position:absolute; left:0; top:.95rem; font-family: var(--font-mono); font-size:1rem; line-height:1; width:1.5rem; text-align:left; } .skin-editorial .u-check.u-use::before{ content:"\\2713"; color: var(--accent); } .skin-editorial .u-check.u-meh::before{ content:"\\00b7"; color: var(--text-dim); font-size:1.4rem; } .skin-editorial .u-check.u-skip::before{ content:"\\2717"; color: var(--text-dim); } .skin-editorial .u-check.u-meh,.skin-editorial .u-check.u-skip{ color: var(--text-dim); } .skin-editorial .u-check.u-skip strong,.skin-editorial .u-check.u-meh strong{ color: var(--text); }
.skin-editorial .u-stats{ display:grid; grid-template-columns: repeat(3,1fr); border-top:1px solid var(--rule); border-bottom:1px solid var(--rule); } .skin-editorial .u-stat{ padding:1.4rem; text-align:center; } .skin-editorial .u-stat + .u-stat{ border-left:1px solid var(--rule); } .skin-editorial .u-fig{ display:block; font-family: var(--font-heading); font-weight:400; font-size:2.9rem; line-height:1; color: var(--accent); letter-spacing:-0.01em; margin-bottom:.7rem; } .skin-editorial .u-fig-lbl{ display:block; font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.1em; font-size:10.5px; line-height:1.4; color: var(--text-dim); }
.skin-editorial .u-statcards{ display:grid; grid-template-columns: repeat(3,1fr); gap:1rem; } .skin-editorial .u-statcard{ padding:1.5rem 1.25rem; border:1px solid var(--rule); border-top:2px solid var(--accent); border-radius:2px; text-align:center; background: rgba(212,196,160,0.03); } .skin-editorial .u-statcard-fig{ display:block; font-family: var(--font-heading); font-weight:400; font-size:2.8rem; line-height:1; color: var(--text-bright); letter-spacing:-0.01em; margin-bottom:.7rem; } .skin-editorial .u-statcard-lbl{ display:block; font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.1em; font-size:10.5px; line-height:1.4; color: var(--text-dim); }
.skin-editorial .u-bignum{ display:grid; grid-template-columns:auto 1fr; align-items:center; column-gap:1.8rem; row-gap:.5rem; padding:1.6rem 0; border-top:1px solid var(--rule); border-bottom:1px solid var(--rule); } .skin-editorial .u-bignum-fig{ font-family: var(--font-heading); font-weight:400; font-size: clamp(4rem,12vw,6.5rem); line-height:0.86; color: var(--accent); letter-spacing:-0.02em; grid-row: span 2; } .skin-editorial .u-bignum-u{ font-size:.45em; vertical-align:super; color: var(--text-dim); } .skin-editorial .u-bignum-cap{ font-family: var(--font-heading); font-size:1.12rem; line-height:1.45; color: var(--text); align-self:end; } .skin-editorial .u-bignum-src{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.12em; font-size:10.5px; color: var(--text-dim); align-self:start; } .skin-editorial .u-bignum-src::before{ content:"\\2014 "; color: var(--accent); }
.skin-editorial .u-strip{ display:flex; flex-wrap:wrap; align-items:baseline; gap:0 1.6rem; padding:1rem 0; border-top:1px solid var(--rule); border-bottom:1px solid var(--rule); } .skin-editorial .u-strip-item{ font-family: var(--font-heading); font-size:.98rem; color: var(--text-dim); display:inline-flex; align-items:baseline; gap:.5em; position:relative; padding-right:1.6rem; } .skin-editorial .u-strip-item:not(:last-child)::after{ content:"\\00b7"; position:absolute; right:0; color: var(--accent); } .skin-editorial .u-strip-item b{ font-weight:400; font-size:1.5rem; color: var(--accent); line-height:1; }
.skin-editorial .u-pq{ margin:0; padding:.4rem 0 .4rem 1.8rem; border-left:2px solid var(--accent); font-family: var(--font-heading); font-style:italic; font-weight:400; font-size: clamp(1.5rem,3.4vw,2rem); line-height:1.34; color: var(--text-bright); } .skin-editorial .u-pq-cite{ display:block; margin-top:1.1rem; font-family: var(--font-mono); font-style:normal; text-transform:uppercase; letter-spacing:.14em; font-size:11px; color: var(--text-dim); } .skin-editorial .u-pq-cite::before{ content:"\\2766"; color: var(--accent); margin-right:.6em; font-size:1.1em; }
.skin-editorial .u-quote{ margin:0; padding:0; text-align:center; } .skin-editorial .u-quote::before{ content:"\\2766"; display:block; color: var(--accent); font-size:1.3rem; margin-bottom:1rem; } .skin-editorial .u-quote p{ font-family: var(--font-heading); font-size: clamp(1.4rem,3vw,1.8rem); line-height:1.4; color: var(--text-bright); margin:0; }
.skin-editorial .u-divider{ border:0; height:auto; text-align:center; margin:.5rem 0; overflow:visible; } .skin-editorial .u-divider::before{ content:"\\2766"; display:inline-block; color: var(--accent); font-size:1.2rem; position:relative; } .skin-editorial .u-divider::after{ content:""; display:block; height:1px; background: var(--rule); width:100%; margin-top:-0.7em; position:relative; z-index:-1; }
.skin-editorial .u-sechead{ padding-bottom:.6rem; border-bottom:1px solid var(--rule); } .skin-editorial .u-sechead-k{ margin:0 0 .7rem; } .skin-editorial .u-sechead-h{ font-family: var(--font-heading); font-weight:400; font-size: clamp(1.9rem,4vw,2.5rem); line-height:1.1; letter-spacing:-0.01em; color: var(--text-bright); margin:0; }
.skin-editorial .u-citep{ font-family: var(--font-heading); font-size:1.05rem; line-height:1.55; color: var(--text); margin:0; } .skin-editorial .u-src{ font-family: var(--font-mono); font-size:12px; margin:0 .3em; } .skin-editorial .u-grade{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.1em; font-size:10px; font-weight:600; padding-left:.6em; margin-left:.3em; border-left:1px solid var(--rule); } .skin-editorial .u-grade::before{ margin-right:.4em; } .skin-editorial .u-grade-a{ color: var(--accent); } .skin-editorial .u-grade-a::before{ content:"\\2713"; } .skin-editorial .u-grade-c{ color: var(--text-dim); } .skin-editorial .u-grade-c::before{ content:"\\2013"; }
.skin-editorial .u-fnp{ font-family: var(--font-heading); font-size:1.05rem; line-height:1.6; color: var(--text); margin:0; } .skin-editorial .u-cite{ font-size:.62em; vertical-align:super; line-height:0; margin-left:.1em; } .skin-editorial .u-cite a{ font-family: var(--font-mono); text-decoration:none; color: var(--accent); padding:0 .15em; }
.skin-editorial .u-table{ width:100%; border-collapse:collapse; font-family: var(--font-heading); font-size:1.02rem; } .skin-editorial .u-table thead th{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.1em; font-size:11px; font-weight:600; color: var(--accent); text-align:left; padding:0 .9rem .7rem; border-bottom:2px solid var(--rule); } .skin-editorial .u-table thead th:last-child,.skin-editorial .u-table td:last-child{ text-align:right; } .skin-editorial .u-table tbody td{ padding:.8rem .9rem; border-bottom:1px solid var(--rule); color: var(--text); vertical-align:baseline; } .skin-editorial .u-table tbody tr:last-child td{ border-bottom:2px solid var(--rule); } .skin-editorial .u-table td.u-num{ color: var(--text-bright); text-align:right; }
.skin-editorial .u-table tr.u-feature td{ background: rgba(212,196,160,0.07); color: var(--text-bright); } .skin-editorial .u-table tr.u-feature td:first-child{ position:relative; } .skin-editorial .u-table tr.u-feature td:first-child::before{ content:"\\2766"; color: var(--accent); font-size:.8em; margin-right:.5em; } .skin-editorial .u-table tbody td:last-child{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.08em; font-size:10.5px; color: var(--text-dim); }
.skin-editorial .u-cards{ display:grid; grid-template-columns: repeat(3,1fr); gap:1.1rem; } .skin-editorial .u-card{ padding:1.4rem 1.3rem; border:1px solid var(--rule); border-radius:2px; background: rgba(232,226,214,0.02); } .skin-editorial .u-card-h{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.13em; font-size:11.5px; font-weight:600; color: var(--accent); margin:0 0 .7rem; padding-bottom:.55rem; border-bottom:1px solid rgba(212,196,160,0.2); } .skin-editorial .u-card-p{ font-family: var(--font-heading); font-size:1rem; line-height:1.5; color: var(--text); margin:0; }
.skin-editorial .u-entries{ border-top:1px solid var(--rule); } .skin-editorial .u-entry{ display:grid; grid-template-columns:5rem 1fr; gap:0 1.8rem; padding:1.5rem 0; border-bottom:1px solid var(--rule); } .skin-editorial .u-entry-num{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.1em; font-size:11px; color: var(--accent); padding-top:.5rem; grid-row: span 2; } .skin-editorial .u-entry-h{ font-family: var(--font-heading); font-weight:400; font-size:1.45rem; line-height:1.22; color: var(--text-bright); margin:0 0 .5rem; } .skin-editorial .u-entry-p{ font-family: var(--font-heading); font-size:1.02rem; line-height:1.5; color: var(--text-dim); margin:0; }
.skin-editorial .u-steps{ list-style:none; counter-reset:u-step; margin:0; padding:0; } .skin-editorial .u-step{ counter-increment:u-step; position:relative; padding:0 0 1.3rem 3.4rem; margin-bottom:1.3rem; border-bottom:1px solid var(--rule); } .skin-editorial .u-step:last-child{ border-bottom:0; margin-bottom:0; padding-bottom:0; } .skin-editorial .u-step::before{ content: counter(u-step, decimal-leading-zero); position:absolute; left:0; top:-0.1rem; font-family: var(--font-heading); font-size:1.9rem; line-height:1; color: var(--accent); } .skin-editorial .u-step-h{ display:block; font-family: var(--font-heading); font-size:1.22rem; color: var(--text-bright); margin-bottom:.3rem; } .skin-editorial .u-step-p{ font-family: var(--font-heading); font-size:1rem; line-height:1.5; color: var(--text-dim); margin:0; }
.skin-editorial .u-toc{ border-top:2px solid var(--rule); border-bottom:2px solid var(--rule); padding:1.3rem 0; } .skin-editorial .u-toc-k{ margin:0 0 1rem; } .skin-editorial .u-toc-list{ list-style:none; margin:0; padding:0; } .skin-editorial .u-toc-list li + li{ border-top:1px solid var(--rule); } .skin-editorial .u-toc-row{ display:flex; align-items:baseline; justify-content:space-between; gap:1rem; padding:.7rem 0; text-decoration:none; color: var(--text); transition: color .15s ease; } .skin-editorial .u-toc-row:hover{ color: var(--accent-hover); } .skin-editorial .u-toc-name{ font-family: var(--font-heading); font-size:1.15rem; display:inline-flex; align-items:baseline; gap:.9rem; } .skin-editorial .u-toc-n{ font-family: var(--font-mono); font-size:11px; letter-spacing:.08em; color: var(--accent); } .skin-editorial .u-toc-m{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.1em; font-size:10.5px; color: var(--text-dim); white-space:nowrap; }
.skin-editorial .u-collapse{ border-top:1px solid var(--rule); border-bottom:1px solid var(--rule); padding:1rem 0; } .skin-editorial .u-collapse-s{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.13em; font-size:11.5px; font-weight:600; color: var(--accent); cursor:pointer; list-style:none; display:flex; align-items:center; gap:.7rem; } .skin-editorial .u-collapse-s::-webkit-details-marker{ display:none; } .skin-editorial .u-collapse-s::before{ content:"+"; font-family: var(--font-mono); font-size:1.1rem; color: var(--accent); width:1ch; display:inline-block; } .skin-editorial .u-collapse[open] .u-collapse-s::before{ content:"\\2013"; } .skin-editorial .u-collapse[open] .u-collapse-s{ margin-bottom:1rem; } .skin-editorial .u-collapse-list{ margin:0; padding:0 0 0 1.4rem; font-family: var(--font-heading); font-size:.98rem; line-height:1.55; color: var(--text); } .skin-editorial .u-collapse-list li{ margin-bottom:.7rem; } .skin-editorial .u-collapse-list b{ color: var(--text-bright); }
.skin-editorial .u-dossier{ display:grid; grid-template-columns: minmax(0,13rem) 1fr; gap:1.8rem; align-items:start; padding-top:1.2rem; border-top:2px solid var(--rule); } .skin-editorial .u-dossier-media{ margin:0; } .skin-editorial .u-dossier-img{ display:block; width:100%; height:auto; border:1px solid var(--rule); border-radius:2px; } .skin-editorial .u-dossier-cap{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.1em; font-size:10px; color: var(--text-dim); margin-top:.6rem; } .skin-editorial .u-dossier-eyebrow{ margin:0 0 .5rem; } .skin-editorial .u-dossier-name{ font-family: var(--font-heading); font-weight:400; font-size:2rem; line-height:1.05; color: var(--text-bright); margin:0 0 1.1rem; padding-bottom:.8rem; border-bottom:1px solid var(--rule); } .skin-editorial .u-dossier-stat{ margin-bottom:1rem; } .skin-editorial .u-dossier-fig{ display:block; font-family: var(--font-heading); font-size:2.6rem; line-height:1; color: var(--accent); letter-spacing:-0.01em; margin-bottom:.45rem; } .skin-editorial .u-dossier-figlbl{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.1em; font-size:10.5px; color: var(--text-dim); } .skin-editorial .u-dossier-lead{ font-family: var(--font-heading); font-style:italic; font-size:1.08rem; line-height:1.5; color: var(--text); margin:0; }
.skin-editorial .u-defs{ margin:0; border-top:1px solid var(--rule); } .skin-editorial .u-defs-t{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.12em; font-size:11.5px; font-weight:600; color: var(--accent); padding-top:1rem; } .skin-editorial .u-defs-d{ font-family: var(--font-heading); font-size:1.08rem; line-height:1.5; color: var(--text); margin:.4rem 0 1rem; padding-bottom:1rem; border-bottom:1px solid var(--rule); }
.skin-editorial .u-board{ border-top:2px solid var(--rule); border-bottom:2px solid var(--rule); padding:1.3rem 0; } .skin-editorial .u-board-k{ margin:0 0 1rem; } .skin-editorial .u-board-list{ list-style:none; counter-reset:u-board; margin:0; padding:0; } .skin-editorial .u-board-row{ counter-increment:u-board; display:flex; align-items:baseline; gap:.5rem; padding:.65rem 0; border-bottom:1px solid var(--rule); } .skin-editorial .u-board-row:last-child{ border-bottom:0; } .skin-editorial .u-board-row::before{ content: counter(u-board); font-family: var(--font-mono); font-size:11px; color: var(--accent); width:1.5em; flex:none; } .skin-editorial .u-board-name{ font-family: var(--font-heading); font-size:1.12rem; color: var(--text-bright); white-space:nowrap; } .skin-editorial .u-board-name i{ font-style:italic; font-size:.85em; color: var(--text-dim); } .skin-editorial .u-board-dots{ flex:1 1 auto; align-self:center; border-bottom:1px dotted var(--rule); height:0; margin:0 .3rem; } .skin-editorial .u-board-val{ font-family: var(--font-mono); font-size:13px; letter-spacing:.04em; color: var(--accent); white-space:nowrap; }
.skin-editorial .u-kpis{ display:grid; grid-template-columns: repeat(3,1fr); border-top:1px solid var(--rule); border-bottom:1px solid var(--rule); } .skin-editorial .u-kpi{ padding:1.5rem 1.2rem; text-align:center; } .skin-editorial .u-kpi + .u-kpi{ border-left:1px solid var(--rule); } .skin-editorial .u-kpi-lbl{ display:block; font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.12em; font-size:10.5px; color: var(--text-dim); margin-bottom:.7rem; } .skin-editorial .u-kpi-val{ display:block; font-family: var(--font-heading); font-weight:400; font-size:2.6rem; line-height:1; color: var(--text-bright); letter-spacing:-0.01em; margin-bottom:.5rem; } .skin-editorial .u-kpi-sub{ display:block; font-family: var(--font-heading); font-style:italic; font-size:.92rem; line-height:1.35; color: var(--text-dim); } .skin-editorial .u-kpi-main .u-kpi-val{ color: var(--accent); } .skin-editorial .u-kpi-main .u-kpi-lbl{ color: var(--accent); }
.skin-editorial .u-spec{ margin:0; border-top:2px solid var(--rule); border-bottom:2px solid var(--rule); } .skin-editorial .u-spec-k{ margin:0; padding:1rem 0; border-bottom:1px solid var(--rule); } .skin-editorial .u-spec-row{ display:grid; grid-template-columns:9rem 1fr; gap:1.2rem; padding:.85rem 0; border-bottom:1px solid var(--rule); } .skin-editorial .u-spec-row:last-child{ border-bottom:0; } .skin-editorial .u-spec-dt{ font-family: var(--font-mono); text-transform:uppercase; letter-spacing:.1em; font-size:11px; color: var(--text-dim); padding-top:.15em; } .skin-editorial .u-spec-dd{ font-family: var(--font-heading); font-size:1.05rem; line-height:1.45; color: var(--text); margin:0; } .skin-editorial .u-spec-em{ color: var(--accent); font-style:italic; }
@media (max-width:640px){ .skin-editorial .u-debate-sides{ grid-template-columns:1fr; gap:1.4rem; } .skin-editorial .u-debate-sides::before{ display:none; } .skin-editorial .u-statcards,.skin-editorial .u-cards{ grid-template-columns:1fr; } .skin-editorial .u-stats,.skin-editorial .u-kpis{ grid-template-columns:1fr; } .skin-editorial .u-stat + .u-stat,.skin-editorial .u-kpi + .u-kpi{ border-left:0; border-top:1px solid var(--rule); } .skin-editorial .u-dossier{ grid-template-columns:1fr; } .skin-editorial .u-bignum{ grid-template-columns:1fr; } .skin-editorial .u-bignum-fig{ grid-row:auto; } }
`;
