(async function(){'use strict';const {watchConnectedStage}=await import('/chain-reaction/candidates/connected-stage-observer.mjs');let observer,completed=[];function observe(){const d=definitions[active];return watchConnectedStage(sim,{...d,constraintSteps:d.constraintSteps||[],transferOrder:d.transferOrder||d.steps.map(s=>s.id),suspense:d.suspense||null});}const CR=window.ChainReaction,canvas=document.getElementById('machine'),status=document.getElementById('status'),pauseButton=document.getElementById('pause'),followButton=document.getElementById('follow'),soundButton=document.getElementById('sound'),title=document.getElementById('stage-title'),frontier=document.getElementById('frontier'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let view,definitions,active=0,sim,nextSim,previous=[],accumulator=0,last=performance.now(),paused=reduced||new URLSearchParams(location.search).get('paused')==='1',ended=false,ready=false,generation=0,following=true,customCamera=null,heroOffset=0,maxWorlds=0,sound,hiddenPause=false,firstMotionMs=null;
 let firstVisit=true;try{firstVisit=localStorage.getItem('chain-reaction-connected-stage')===null;}catch{}firstVisit=firstVisit&&!location.hash&&!reduced;
 function save(){try{localStorage.setItem('chain-reaction-connected-stage',String(active+1));}catch{}}
 function readSaved(){try{return Number(localStorage.getItem('chain-reaction-connected-stage'))||1;}catch{return 1;}}
 function requested(){const m=location.hash.match(/stage=(\d+)/);return m?Number(m[1]):reduced?1:readSaved();}
 function updateUI(){pauseButton.textContent=paused?'Play':'Pause';pauseButton.setAttribute('aria-pressed',String(paused));pauseButton.hidden=ended;followButton.hidden=following;frontier.hidden=!ended;title.textContent=definitions[active].title;title.classList.toggle('faded',ended||(sim&&sim.tick/240>=3));}
 function sample(nodes,t){let i=nodes.findIndex(p=>p.time>=t);if(i<0)return nodes.at(-1);if(i===0)return nodes[0];const a=nodes[i-1],b=nodes[i],u=Math.max(0,Math.min(1,(t-a.time)/(b.time-a.time))),s=reduced?1:u*u*u*(10+u*(-15+6*u));return {x:a.x+(b.x-a.x)*s,y:a.y+(b.y-a.y)*s,width:Math.exp(Math.log(a.width)+s*Math.log(b.width/a.width)),minHeight:Math.exp(Math.log(a.minHeight)+s*Math.log(b.minHeight/a.minHeight))};}
 function camera(){if(!following)return customCamera;const path=firstVisit&&active===0?definitions[active].verified.camera.revealNodes:definitions[active].verified.camera.nodes;const c=sample(path,sim?Math.max(0,(sim.tick-1+accumulator*240)/240):0);return {...c,x:c.x+active*16};}
 function drawPose(){if(!sim)return;const states=sim.state(),alpha=accumulator*240,display=states.map((p,i)=>{const a=previous[i]||p;let delta=p.angle-a.angle;if(delta>Math.PI)delta-=2*Math.PI;if(delta<-Math.PI)delta+=2*Math.PI;return {...p,x:a.x+(p.x-a.x)*alpha,y:a.y+(p.y-a.y)*alpha,angle:a.angle+delta*alpha};});view.apply(active,display,heroOffset);view.setCamera(camera());}
 async function warmNext(own=generation){if(active>=definitions.length-1)return;const n=await CR.physics.create(definitions[active+1]);if(own!==generation){n.dispose();return;}nextSim?.dispose();nextSim=n;maxWorlds=Math.max(maxWorlds,(sim?1:0)+1);}
 async function start(index){const own=++generation;ready=false;sim?.dispose();nextSim?.dispose();sim=nextSim=null;active=Math.max(0,Math.min(definitions.length-1,index-1));for(let i=0;i<definitions.length;i++){view.apply(i,i<active?definitions[i].verified.spent:definitions[i].verified.armed);view.hideHero?.(i,i<active);view.hideEntry?.(i,i>active);}heroOffset=0;const candidate=await CR.physics.create(definitions[active]);if(own!==generation){candidate.dispose();return;}sim=candidate;observer=observe();completed=[];previous=sim.state();accumulator=0;ended=false;following=true;customCamera=null;ready=true;last=performance.now();save();updateUI();drawPose();view.draw();warmNext(own);sound?.start(definitions[active],sim.tick/240);}
 function handoff(){const report=observer.report();if(!report.pass)throw Error('Physical handoff verification failed');completed.push({stage:active+1,tick:sim.tick,report,snapshot:Array.from(sim.snapshot())});const exiting=sim.state().find(p=>p.id===definitions[active].exitId);view.apply(active,sim.state(),heroOffset);sim.dispose();sim=null;if(active===definitions.length-1){ended=paused=true;ready=false;const end=definitions[active].verified.camera.nodes.at(-1);view.setCamera({...end,x:end.x+active*16});sound?.pause();updateUI();return;}
  view.hideHero?.(active,true);active++;view.hideEntry?.(active,false);sim=nextSim;nextSim=null;if(!sim)throw Error('Next physics world is not ready');observer=observe();heroOffset=exiting.angle;previous=sim.state();save();updateUI();sound?.start(definitions[active],0);warmNext();
 }
 function setPaused(value){paused=value;view?.invalidate();last=performance.now();if(paused)sound?.pause();else if(sim)sound?.start(definitions[active],sim.tick/240);updateUI();}
 function replay(){firstVisit=false;history.replaceState(null,'','#stage=1');start(1).then(()=>setPaused(false));}
 function follow(){following=true;customCamera=null;if(ended){const c=definitions[active].verified.camera.nodes.at(-1);view.setCamera({...c,x:c.x+active*16});}else drawPose();updateUI();}
 function manual(){if(following){customCamera=view.framing();following=false;updateUI();}}
 try{
  if(!window.WebAssembly||!window.THREE||!canvas.getContext('webgl2'))throw Error('This machine needs WebGL2 and WebAssembly.');
  const manifest=await fetch('/chain-reaction/stages/viewer/index.json?v=1').then(r=>{if(!r.ok)throw Error('Stage index unavailable');return r.json();});definitions=await Promise.all(manifest.stages.map(d=>fetch('/chain-reaction/stages/viewer/'+d.file+'?v='+d.hash.slice(0,12)).then(r=>{if(!r.ok)throw Error('Stage unavailable');return r.json();})));view=CR.makeView(canvas,definitions);view.draw();sound=CR.makeSound?.();
  if(document.body.dataset.soundReview==='true'||new URLSearchParams(location.search).get('sound-review')==='1')soundButton.hidden=false;
  await start(requested());document.getElementById('still').hidden=true;status.hidden=true;
  pauseButton.onclick=()=>{if(ended)replay();else setPaused(!paused);};followButton.onclick=follow;soundButton.onclick=async()=>{const enabled=await sound.toggle();soundButton.textContent=enabled?'Sound on':'Sound off';soundButton.setAttribute('aria-pressed',String(enabled));try{localStorage.setItem('chain-reaction-sound',String(enabled));}catch{}if(enabled&&!paused)sound.start(definitions[active],sim.tick/240);};
  document.getElementById('restart').onclick=replay;window.addEventListener('hashchange',()=>{const i=requested();start(i).then(()=>setPaused(reduced));});window.addEventListener('resize',()=>{view.resize();drawPose();view.draw();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){hiddenPause=!paused;setPaused(true);}else if(hiddenPause){hiddenPause=false;setPaused(false);}});
  canvas.addEventListener('wheel',e=>{e.preventDefault();manual();const factor=Math.exp(e.deltaY*.0015),c=customCamera;customCamera={...c,width:Math.max(3,Math.min(70,c.width*factor)),minHeight:Math.max(2,Math.min(40,c.minHeight*factor))};view.setCamera(customCamera);},{passive:false});
  const pointers=new Map();let moved=false,startPoint=null,initialPinch=null;
  canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});moved=false;startPoint={x:e.clientX,y:e.clientY};if(pointers.size===2){manual();const a=[...pointers.values()];initialPinch={distance:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),camera:{...customCamera}};}});
  canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const before=pointers.get(e.pointerId),dx=e.clientX-before.x,dy=e.clientY-before.y;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(Math.hypot(e.clientX-startPoint.x,e.clientY-startPoint.y)>4)moved=true;if(!moved)return;manual();if(pointers.size===2&&initialPinch){const a=[...pointers.values()],distance=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),f=initialPinch.distance/distance;customCamera={...initialPinch.camera,width:Math.max(3,Math.min(70,initialPinch.camera.width*f)),minHeight:Math.max(2,Math.min(40,initialPinch.camera.minHeight*f))};}else{const height=Math.max(customCamera.minHeight,customCamera.width/(canvas.clientWidth/canvas.clientHeight)),width=height*canvas.clientWidth/canvas.clientHeight;customCamera={...customCamera,x:customCamera.x-dx*width/canvas.clientWidth,y:customCamera.y+dy*height/canvas.clientHeight};}view.setCamera(customCamera);});
  function release(e){if(!moved&&!following&&customCamera.width>=28){const rect=canvas.getBoundingClientRect(),p=view.worldAt(e.clientX-rect.left,e.clientY-rect.top);const stage=Math.floor(p.x/16)+1;if(p.y>=0&&p.y<=9&&stage>=1&&stage<=definitions.length)start(stage).then(()=>setPaused(reduced));}pointers.delete(e.pointerId);initialPinch=null;}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);initialPinch=null;});
  document.addEventListener('keydown',e=>{if(e.target.tagName==='BUTTON'||e.target.tagName==='A')return;if(e.code==='Space'){e.preventDefault();if(ended)replay();else setPaused(!paused);}else if(e.key.toLowerCase()==='f')follow();else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'].includes(e.key)){e.preventDefault();manual();const c=customCamera;if(e.key.startsWith('Arrow')){c.x+=e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0;c.y+=e.key==='ArrowUp'?1:e.key==='ArrowDown'?-1:0;}else{const f=e.key==='-'?1.2:1/1.2;c.width=Math.max(3,Math.min(70,c.width*f));c.minHeight=Math.max(2,Math.min(40,c.minHeight*f));}view.setCamera(c);}});
  window.ChainReactionPage={ready:true,observations:()=>sim?observer.report(false):completed.at(-1)?.report,completed:()=>structuredClone(completed),snapshot:()=>sim?Array.from(sim.snapshot()):null,inspect:()=>view.inspect(),quality:()=>view.quality(),async seek(index,t=0){setPaused(true);await start(index);for(let n=0;n<Math.round(t*240);n++){sim.step();observer.sample();}previous=sim.state();accumulator=0;view.apply(active,previous,heroOffset);firstVisit=false;view.setCamera({...sample(definitions[active].verified.camera.nodes,t),x:sample(definitions[active].verified.camera.nodes,t).x+active*16});view.draw();updateUI();return this.state();},state:()=>({stage:active+1,tick:sim?.tick||0,paused,ended,following,maxWorlds,pose:sim?.state(),camera:view.framing()}),metrics:()=>({...view.metrics(),firstMotionMs}),resetMetrics:()=>view.resetMetrics(),play:()=>setPaused(false),pause:()=>setPaused(true),overview(){manual();customCamera={x:definitions.length*8,y:4,width:definitions.length*16+6,minHeight:10};view.setCamera(customCamera);},sound,advance(count){setPaused(true);for(let n=0;n<count&&sim;n++){previous=sim.state();sim.step();observer.sample();if(sim.bodies.get(definitions[active].exitId).translation().x>=16)handoff();}if(sim){previous=sim.state();view.apply(active,previous,heroOffset);view.setCamera(camera());}view.draw();updateUI();return this.state();}};
  function frame(now){const elapsed=Math.min((now-last)/1000,.05);last=now;try{if(ready&&!paused){accumulator+=elapsed;while(accumulator>=CR.physics.DT){previous=sim.state();sim.step();observer.sample();if(firstMotionMs===null)firstMotionMs=performance.now();accumulator-=CR.physics.DT;const q=sim.bodies.get(definitions[active].exitId).translation();if(q.x>=16){handoff();if(!ready)break;}}if(ready){drawPose();sound?.update(sim.tick/240,sim.state(),p=>view.project(p.x+active*16,p.y,p.z||0),canvas.clientWidth);updateUI();}}if(!document.hidden&&(ready&&!paused||view.needsDraw()))view.draw(now,true,sim?sim.tick/240:0,ready&&!paused);}catch(e){setPaused(true);status.hidden=false;status.textContent='The machine paused. Reload to try again.';console.error(e);}requestAnimationFrame(frame);}last=performance.now();requestAnimationFrame(frame);
 }catch(error){document.getElementById('still').hidden=false;status.hidden=false;status.textContent='The moving machine is unavailable. '+error.message;pauseButton.hidden=true;followButton.hidden=true;soundButton.hidden=true;document.getElementById('restart').hidden=true;console.error(error);}
})();
