(async function(){'use strict';
 const {watchConstraints}=await import('/chain-reaction/candidates/constraint-observer.mjs');
 const {drawerConstraints}=await import('/chain-reaction/candidates/drawer-constraint-declarations.mjs');
 const {watchPacing}=await import('/chain-reaction/candidates/pacing-observer.mjs');
 const {drawerSuspense}=await import('/chain-reaction/candidates/drawer-suspense-declaration.mjs');
 const kit=16;
 const CR=window.ChainReaction,canvas=document.getElementById('machine'),status=document.getElementById('status'),pause=document.getElementById('pause'),detail=document.getElementById('detail'),definition=await fetch('/chain-reaction/kits/drawer-outlet-v'+kit+'.json').then(r=>r.json());
 let sim,view,watch,ropes,pacing,paused=true,finished=false,resetting=false,close=false,last=performance.now(),accumulator=0;
 function buttons(){pause.disabled=finished;pause.textContent=finished?'Finished':paused?'Play':'Pause';pause.setAttribute('aria-pressed',String(paused));}
 function camera(){view.setCamera(close?{x:10,y:2,width:11,minHeight:5.5}:{x:8,y:2,width:16.4,minHeight:5.5});detail.textContent=close?'Whole mechanism':'View detail';detail.setAttribute('aria-pressed',String(close));}
 async function reset(){if(resetting)return;resetting=true;try{const next=await CR.physics.create(definition);sim?.dispose();sim=next;watch=CR.events.watch(sim,definition);ropes=watchConstraints(sim,definition,watch,drawerConstraints());pacing=definition.suspense?watchPacing(sim,definition,watch,ropes,drawerSuspense(definition)):null;paused=true;finished=false;accumulator=0;last=performance.now();buttons();view?.apply(0,sim.state());status.textContent='A falling weight opens the drawer and pulls the outlet support.';}finally{resetting=false;}}
 await reset();view=CR.makeView(canvas,[definition]);camera();view.draw();
 pause.onclick=()=>{paused=!paused;last=performance.now();buttons();};document.getElementById('reset').onclick=reset;detail.onclick=()=>{close=!close;camera();};
 addEventListener('resize',()=>view.resize());document.addEventListener('visibilitychange',()=>{last=performance.now();accumulator=0;});
 function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(!paused&&!finished&&!resetting&&!document.hidden){accumulator+=dt;while(accumulator>=CR.physics.DT){sim.step();watch.sample();ropes.sample();pacing?.sample();accumulator-=CR.physics.DT;if(sim.bodies.get(definition.exitId).translation().x>=16||sim.tick>=6000){finished=true;paused=true;buttons();status.textContent=sim.bodies.get(definition.exitId).translation().x>=16?'The drawer has released the next marble.':'The mechanism stopped before releasing the marble.';break;}}view.apply(0,sim.state());}if(view.needsDraw())view.draw(now,false,sim.tick/240,!paused&&!finished);requestAnimationFrame(frame);}
 window.ChainReactionDrawerOutlet={ready:true,definition,quality:()=>view.quality(),inspect:()=>view.inspect(),state:()=>({tick:sim.tick,paused,finished,close,poses:sim.state(),events:watch.report(false),ropes:ropes.report(),pacing:pacing?.report()}),async seek(tick){if(resetting)return;resetting=true;paused=true;try{const next=await CR.physics.create(definition);sim.dispose();sim=next;watch=CR.events.watch(sim,definition);ropes=watchConstraints(sim,definition,watch,drawerConstraints());pacing=definition.suspense?watchPacing(sim,definition,watch,ropes,drawerSuspense(definition)):null;for(let n=0;n<Math.min(tick,6000);n++){sim.step();watch.sample();ropes.sample();pacing?.sample();if(sim.bodies.get(definition.exitId).translation().x>=16)break;}finished=sim.bodies.get(definition.exitId).translation().x>=16||sim.tick>=6000;accumulator=0;last=performance.now();buttons();view.apply(0,sim.state());view.draw();status.textContent=finished?(sim.bodies.get(definition.exitId).translation().x>=16?'The drawer has released the next marble.':'The mechanism stopped before releasing the marble.'):'A falling weight opens the drawer and pulls the outlet support.';}finally{resetting=false;}}};requestAnimationFrame(frame);
})();
