(async function(){'use strict';
 const CR=window.ChainReaction,canvas=document.getElementById('machine'),status=document.getElementById('status'),pause=document.getElementById('pause'),detail=document.getElementById('detail'),definition=await fetch('/chain-reaction/kits/drawer-latch-v12.json').then(r=>r.json());
 let sim,view,watch,paused=true,finished=false,resetting=false,close=false,last=performance.now(),accumulator=0;
 function buttons(){pause.disabled=finished;pause.textContent=finished?'Finished':paused?'Play':'Pause';pause.setAttribute('aria-pressed',String(paused));}
 function camera(){view.setCamera(close?{x:8.7,y:2,width:5.4,minHeight:4.7}:{x:8,y:2,width:16.4,minHeight:5.5});detail.textContent=close?'Whole mechanism':'View detail';detail.setAttribute('aria-pressed',String(close));}
 async function reset(){if(resetting)return;resetting=true;try{const next=await CR.physics.create(definition);sim?.dispose();sim=next;watch=CR.events.watch(sim,definition);paused=true;finished=false;accumulator=0;last=performance.now();buttons();view?.apply(0,sim.state());status.textContent='One marble withdraws the support.';}finally{resetting=false;}}
 await reset();view=CR.makeView(canvas,[definition]);camera();view.draw();
 pause.onclick=()=>{paused=!paused;last=performance.now();buttons();};document.getElementById('reset').onclick=reset;detail.onclick=()=>{close=!close;camera();};
 addEventListener('resize',()=>view.resize());document.addEventListener('visibilitychange',()=>{last=performance.now();accumulator=0;});
 function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(!paused&&!finished&&!resetting&&!document.hidden){accumulator+=dt;while(accumulator>=CR.physics.DT){sim.step();watch.sample();accumulator-=CR.physics.DT;if(sim.tick>=2400){finished=true;paused=true;buttons();status.textContent='The weight has opened the drawer.';break;}}view.apply(0,sim.state());}if(view.needsDraw())view.draw(now,false,sim.tick/240,!paused&&!finished);requestAnimationFrame(frame);}
 window.ChainReactionDrawerRelease={ready:true,definition,inspect:()=>view.inspect(),state:()=>({tick:sim.tick,paused,finished,close,poses:sim.state(),events:watch.report(false)}),async seek(tick){if(resetting)return;resetting=true;paused=true;try{const next=await CR.physics.create(definition);sim.dispose();sim=next;watch=CR.events.watch(sim,definition);for(let n=0;n<Math.min(tick,2400);n++){sim.step();watch.sample();}finished=sim.tick>=2400;accumulator=0;last=performance.now();buttons();view.apply(0,sim.state());view.draw();status.textContent=finished?'The weight has opened the drawer.':'One marble withdraws the support.';}finally{resetting=false;}}};requestAnimationFrame(frame);
})();
