(async function(){'use strict';
 const CR=window.ChainReaction,canvas=document.getElementById('machine'),status=document.getElementById('status'),pause=document.getElementById('pause'),definition=await fetch('/chain-reaction/kits/drawer-bearing-v1.json').then(r=>r.json());
 let sim,view,paused=true,finished=false,resetting=false,last=performance.now(),accumulator=0;
 function buttons(){pause.disabled=finished;pause.textContent=finished?'Finished':paused?'Play':'Pause';pause.setAttribute('aria-pressed',String(paused));}
 async function reset(){if(resetting)return;resetting=true;try{const next=await CR.physics.create(definition);sim?.dispose();sim=next;paused=true;finished=false;accumulator=0;last=performance.now();buttons();view?.apply(0,sim.state());status.textContent='A falling weight pulls the drawer.';}finally{resetting=false;}}
 await reset();view=CR.makeView(canvas,[definition]);view.setCamera(definition.view);view.draw();
 pause.onclick=()=>{paused=!paused;last=performance.now();buttons();};document.getElementById('reset').onclick=reset;
 addEventListener('resize',()=>view.resize());document.addEventListener('visibilitychange',()=>{last=performance.now();accumulator=0;});
 function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(!paused&&!finished&&!resetting&&!document.hidden){accumulator+=dt;while(accumulator>=CR.physics.DT){sim.step();accumulator-=CR.physics.DT;if(sim.bodies.get('drawer').translation().x-definition.parts.find(p=>p.id==='drawer').x>.645||sim.tick>=2400){finished=true;paused=true;buttons();status.textContent=sim.tick<2400?'The drawer rests at its stop.':'The drawer has not reached its stop.';break;}}view.apply(0,sim.state());}if(view.needsDraw())view.draw(now,false,sim.tick/240,!paused&&!finished);requestAnimationFrame(frame);}
 window.ChainReactionDrawer={ready:true,definition,state:()=>({tick:sim.tick,paused,finished,poses:sim.state()}),async seek(tick){if(resetting)return;resetting=true;paused=true;try{const next=await CR.physics.create(definition);sim.dispose();sim=next;for(let n=0;n<tick;n++)sim.step();finished=sim.bodies.get('drawer').translation().x-definition.parts.find(p=>p.id==='drawer').x>.645;accumulator=0;last=performance.now();buttons();view.apply(0,sim.state());view.draw();status.textContent=finished?'The drawer rests at its stop.':'A falling weight pulls the drawer.';}finally{resetting=false;}}};requestAnimationFrame(frame);
})();
