(async function(){'use strict';
 const CR=window.ChainReaction,canvas=document.getElementById('machine'),status=document.getElementById('status'),pause=document.getElementById('pause'),detail=document.getElementById('detail');
 const definition=await fetch('/chain-reaction/kits/stopped-rocker-v3.json').then(r=>{if(!r.ok)throw Error('Rocker definition unavailable');return r.json();});
 let sim,view,watch,paused=true,finished=false,resetting=false,close=false,last=performance.now(),accumulator=0;
 function buttons(){pause.disabled=finished;pause.textContent=finished?'Finished':paused?'Play':'Pause';pause.setAttribute('aria-pressed',String(paused));}
 function camera(){view.setCamera(close?{x:6.5,y:1.1,width:7.8,minHeight:2.6}:{x:5.2,y:1.1,width:11.4,minHeight:3});detail.textContent=close?'Whole mechanism':'View detail';detail.setAttribute('aria-pressed',String(close));}
 function caption(){const p=sim.bodies.get(definition.entryId).translation(),landed=p.x>7.8&&p.y<.68;status.textContent=finished?(landed?'The marble has settled in the felt tray.':'The marble stopped before reaching the felt tray.'):landed?'A soft landing.':watch.report(false).events[0].motionTick!==null?'The weighted tray lowers the marble beneath the stop.':'The marble rolls toward the weighted tray.';}
 async function reset(){if(resetting)return;resetting=true;try{const next=await CR.physics.create(definition);sim?.dispose();sim=next;watch=CR.events.watch(sim,definition);paused=true;finished=false;accumulator=0;last=performance.now();buttons();view?.apply(0,sim.state());caption();}finally{resetting=false;}}
 await reset();view=CR.makeView(canvas,[definition]);camera();view.draw();
 pause.onclick=()=>{paused=!paused;last=performance.now();buttons();};document.getElementById('reset').onclick=reset;detail.onclick=()=>{close=!close;camera();};
 addEventListener('resize',()=>view.resize());document.addEventListener('visibilitychange',()=>{last=performance.now();accumulator=0;});
 function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(!paused&&!finished&&!resetting&&!document.hidden){accumulator+=dt;while(accumulator>=CR.physics.DT){sim.step();watch.sample();accumulator-=CR.physics.DT;if(sim.tick>=2400){finished=true;paused=true;buttons();break;}}view.apply(0,sim.state());caption();}if(view.needsDraw())view.draw(now,false,sim.tick/240,false);requestAnimationFrame(frame);}
 window.ChainReactionRocker={ready:true,definition,quality:()=>view.quality(),state:()=>({tick:sim.tick,paused,finished,close,poses:sim.state(),events:watch.report(false)}),snapshot:()=>Array.from(sim.snapshot()),async seek(tick){if(resetting)return;resetting=true;paused=true;try{const next=await CR.physics.create(definition);sim.dispose();sim=next;watch=CR.events.watch(sim,definition);for(let n=0;n<Math.min(tick,2400);n++){sim.step();watch.sample();}finished=sim.tick>=2400;accumulator=0;last=performance.now();buttons();view.apply(0,sim.state());view.draw();caption();}finally{resetting=false;}}};requestAnimationFrame(frame);
})();
