import assert from 'node:assert/strict';
import {thresholds} from './limits.mjs';
export function bakeCamera(stage,measurement){const end=measurement.exit.time;
 const nodes=stage.stageNumber===1?[{time:0,x:8.9,y:3.25,width:11.2,minHeight:6.7},{time:end-2.6,x:8.9,y:3.25,width:11.2,minHeight:6.7},{time:end,x:16,y:2,width:8,minHeight:4}]:[{time:0,x:0,y:2,width:8,minHeight:4},{time:1.75,x:6.5,y:4.05,width:11.2,minHeight:8.8},{time:end,x:16,y:2,width:8,minHeight:4}];
 const segments=[];for(let i=1;i<nodes.length;i++){const a=nodes[i-1],b=nodes[i],t=b.time-a.time,translationJerk=60*Math.sqrt((b.x-a.x)**2+(b.y-a.y)**2)/(t*t*t),logZoomJerk=60*Math.max(Math.abs(Math.log(b.width/a.width)),Math.abs(Math.log(b.minHeight/a.minHeight)))/(t*t*t);assert(translationJerk<=thresholds.camera.translationJerkCap,'Camera translation jerk');assert(logZoomJerk<=thresholds.camera.logZoomJerkCap,'Camera zoom jerk');segments.push({translationJerk,logZoomJerk});}
 const result={version:1,nodes,segments,framing:[]};if(stage.stageNumber===2){const resume=sampleCamera(nodes,6.1);result.revealNodes=[{time:0,x:0,y:2,width:8,minHeight:4},{time:2.3,x:8,y:4.1,width:54,minHeight:10},{time:3.8,x:8,y:4.1,width:54,minHeight:10},{time:6.1,...resume},{time:end,x:16,y:2,width:8,minHeight:4}];for(let i=1;i<result.revealNodes.length;i++){const a=result.revealNodes[i-1],b=result.revealNodes[i],t=b.time-a.time;assert(60*Math.sqrt((b.x-a.x)**2+(b.y-a.y)**2)/(t*t*t)<=80,'Reveal translation jerk');assert(60*Math.max(Math.abs(Math.log(b.width/a.width)),Math.abs(Math.log(b.minHeight/a.minHeight)))/(t*t*t)<=15,'Reveal zoom jerk');}}
 for(const [pathName,path] of [['follow',nodes],...(result.revealNodes?[['reveal',result.revealNodes]]:[])])for(const view of [{width:1440,height:844},{width:844,height:334},{width:390,height:788}])for(const frame of measurement.eventFrames){const c=sampleCamera(path,frame.time),height=Math.max(c.minHeight,c.width/(view.width/view.height)),distance=height/(2*Math.tan(13.039*Math.PI/360)),f=1/Math.tan(13.039*Math.PI/360);for(const p of frame.points){const depth=distance-((p.y-c.y)*.08715574274765817+(p.z||0)*.9961946980917455),x=(p.x-c.x)*f/(view.width/view.height*depth),y=((p.y-c.y)*.9961946980917455-(p.z||0)*.08715574274765817)*f/depth;result.framing.push({path:pathName,view,step:frame.id,time:frame.time,x,y,pass:Math.abs(x)<=.95&&Math.abs(y)<=.95});}}
 assert(result.framing.every(r=>r.pass),'Camera misses a physical contact: '+JSON.stringify(result.framing.filter(r=>!r.pass)));result.framing={pass:true,samples:result.framing.length,viewports:[{width:1440,height:900},{width:844,height:390},{width:390,height:844}],paths:result.revealNodes?['follow','reveal']:['follow'],maximumNormalizedX:Math.max(...result.framing.map(r=>Math.abs(r.x))),maximumNormalizedY:Math.max(...result.framing.map(r=>Math.abs(r.y)))};return result;
}
export function sampleCamera(nodes,time){let b=nodes.findIndex(p=>p.time>=time);if(b<0)return nodes.at(-1);if(b===0)return nodes[0];const a=nodes[b-1],z=nodes[b],t=(time-a.time)/(z.time-a.time),s=t*t*t*(10+t*(-15+6*t));return {x:a.x+(z.x-a.x)*s,y:a.y+(z.y-a.y)*s,width:Math.exp(Math.log(a.width)+(Math.log(z.width)-Math.log(a.width))*s),minHeight:Math.exp(Math.log(a.minHeight)+(Math.log(z.minHeight)-Math.log(a.minHeight))*s)};}
