import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {serve,browserRun} from './browser.mjs';import {toolLock} from './core.mjs';
const release=await toolLock(),server=await serve(process.env.CHAIN_REACTION_RESEARCH),report=[];
const p95=a=>a.filter(n=>n>=0).sort((a,b)=>a-b)[Math.floor(a.length*.95)],median=a=>a.sort((a,b)=>a-b)[2];
try{await browserRun('chromium',async browser=>{
 for(const profile of [{name:'desktop',width:1440,height:900,cpu:1},{name:'phone',width:844,height:390,cpu:4}]){
  const runs=[];for(let n=0;n<5;n++){
   const context=await browser.newContext({viewport:{width:profile.width,height:profile.height}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const cdp=await context.newCDPSession(page);if(profile.cpu>1)await cdp.send('Emulation.setCPUThrottlingRate',{rate:profile.cpu});await page.goto(server.url+'/chain-reaction.html');await page.waitForFunction(()=>window.ChainReactionPage?.ready);await page.waitForFunction(()=>ChainReactionPage.metrics().firstMotionMs!==null);
   const motion=await page.evaluate(()=>ChainReactionPage.metrics().firstMotionMs);if(profile.cpu===1)assert(motion<2000,'Cold motion exceeded two seconds: '+motion);
   await page.evaluate(()=>ChainReactionPage.seek(3,1));await page.evaluate(()=>ChainReactionPage.play());await page.waitForTimeout(300);await page.evaluate(()=>ChainReactionPage.resetMetrics());await page.waitForTimeout(900);const busy=await page.evaluate(()=>ChainReactionPage.metrics());
   await page.evaluate(()=>ChainReactionPage.overview());await page.waitForTimeout(250);await page.evaluate(()=>ChainReactionPage.resetMetrics());await page.waitForTimeout(900);const overview=await page.evaluate(()=>ChainReactionPage.metrics());runs.push({run:n+1,coldMotionMs:motion,busyP95:p95(busy.frames),overviewP95:p95(overview.frames),busySamples:busy.frames.length,overviewSamples:overview.frames.length,busyDrawCalls:busy.drawCalls,overviewDrawCalls:overview.drawCalls,errors});assert.deepEqual(errors,[]);await context.close();
  }
  const row={profile,runs,busyMedianP95:median(runs.map(r=>r.busyP95)),overviewMedianP95:median(runs.map(r=>r.overviewP95))};row.pass=row.busyMedianP95<=16.7&&row.overviewMedianP95<=16.7;report.push(row);console.log(profile.name,row.busyMedianP95,row.overviewMedianP95,row.pass);
 }
 const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();await page.goto(server.url+'/chain-reaction.html');await page.waitForFunction(()=>window.ChainReactionPage?.ready);await page.evaluate(()=>ChainReactionPage.seek(1,9.425));const handoff=[];for(let i=0;i<16;i++){const s=await page.evaluate(()=>ChainReactionPage.advance(2));handoff.push({frame:i,stage:s.stage,tick:s.tick,camera:s.camera,hero:s.pose?.find(p=>p.id===(s.stage===1?'marble-out':'marble-in')),maxWorlds:s.maxWorlds});await page.screenshot({path:process.env.CHAIN_REACTION_RESEARCH+'/evidence/cycle-5/handoff-'+String(i).padStart(2,'0')+'.png'});}assert(handoff.some(r=>r.stage===1)&&handoff.some(r=>r.stage===2),'Missing handoff capture');assert(handoff.every(r=>r.maxWorlds<=2));await page.evaluate(()=>ChainReactionPage.seek(1,0));await page.evaluate(()=>ChainReactionPage.play());await page.waitForFunction(()=>ChainReactionPage.state().ended,null,{timeout:40000});const final=await page.evaluate(()=>ChainReactionPage.state());assert(final.stage===3&&final.maxWorlds<=2&&final.paused);report.push({type:'continuous',pass:true,final:{stage:final.stage,paused:final.paused,maxWorlds:final.maxWorlds},handoff});await context.close();
 });await writeFile(process.env.CHAIN_REACTION_RESEARCH+'/evidence/cycle-5/film.json',JSON.stringify(report,null,2)+'\n');assert(report.every(r=>r.pass),'Film performance failed');}finally{await server.close();await release();}
