import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';import {resolve} from 'node:path';import {ROOT,physics,moduleURL,hash,toolLock} from './core.mjs';import {serve,browserRun} from './browser.mjs';
const release=await toolLock(),server=await serve(process.env.CHAIN_REACTION_RESEARCH),report=[];
try{
 const stages=await Promise.all([1,2,3].map(async n=>JSON.parse(await readFile(resolve(ROOT,'assets/chain-reaction/stages/'+String(n).padStart(5,'0')+'.json')))));
 for(const engine of ['chromium','webkit'])await browserRun(engine,async browser=>{
  const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});await page.goto(server.url+'/chain-reaction.html');await page.waitForFunction(()=>window.ChainReactionPage?.ready,null,{timeout:30000});assert((await page.evaluate(()=>ChainReactionPage.state())).paused);
  const parity=[];for(const d of stages)for(const mirrored of [false,true]){const recorded=d.verified.orientations.find(r=>r.mirrored===mirrored);const result=await page.evaluate(async({d,mirrored,ticks})=>{if(mirrored)d=ChainReaction.physics.mirror(d);const sim=await ChainReaction.physics.create(d),watch=ChainReaction.events.watch(sim,d);try{for(let n=0;n<ticks;n++){sim.step();watch.sample();}return {snapshot:Array.from(sim.snapshot()),events:watch.report()};}finally{sim.dispose();}},{d,mirrored,ticks:recorded.exit.tick});assert.equal(hash(Uint8Array.from(result.snapshot)),recorded.snapshotHash,'Stage parity');assert.deepEqual(result.events,recorded.events,'Transfer parity');parity.push({stage:d.stageNumber,mirrored,pass:true});}
  for(const view of [{width:1440,height:900},{width:844,height:390},{width:390,height:844}]){await page.setViewportSize(view);await page.evaluate(()=>ChainReactionPage.seek(1,0));await page.waitForTimeout(850);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const targets=await page.locator('button:visible,.cr-home').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().height));assert(targets.every(h=>h>=44));await page.screenshot({path:process.env.CHAIN_REACTION_RESEARCH+'/evidence/cycle-5/'+engine+'-cover-'+view.width+'.png'});}
  await page.setViewportSize({width:844,height:390});await page.locator('#pause').click();await page.waitForFunction(()=>ChainReactionPage.state().tick>30);await page.locator('#pause').click();const tick=await page.evaluate(()=>ChainReactionPage.state().tick);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>ChainReactionPage.state().tick),tick);await page.locator('#machine').focus();await page.keyboard.press('ArrowRight');assert((await page.evaluate(()=>ChainReactionPage.state())).following===false);await page.locator('#follow').click();assert((await page.evaluate(()=>ChainReactionPage.state())).following);await page.keyboard.press('Space');await page.waitForFunction(()=>ChainReactionPage.state().tick>60);await page.keyboard.press('Space');
  await page.goto(server.url+'/chain-reaction.html#stage=3');await page.waitForFunction(()=>window.ChainReactionPage?.ready);assert.equal((await page.evaluate(()=>ChainReactionPage.state())).stage,3);assert(await page.locator('#sound').isHidden());await page.locator('#about-toggle').click();assert(await page.locator('#about').isVisible());assert.equal(await page.locator('#share').getAttribute('href'),'#stage=3');assert.deepEqual(errors,[]);report.push({engine,version:browser.version(),pass:true,parity,checks:['reduced motion paused','three viewports','44px targets','no overflow','play/pause','keyboard pan/follow','deep link','about and share','public sound hidden','zero browser errors']});await context.close();
 });
 console.log(JSON.stringify(report,null,2));await writeFile(process.env.CHAIN_REACTION_RESEARCH+'/evidence/cycle-5/slice-smoke.json',JSON.stringify(report,null,2)+'\n');
}finally{await server.close();await release();}
