import {physics,moduleURL,hash} from './core.mjs';
import {initialGeometry,depthLayers} from './geometry.mjs';
import {thresholds} from './limits.mjs';
export async function measureStage(d,mirrored=false,geometry=true,trace=false){if(mirrored)d=physics.mirror(d);const s=await physics.create(d,moduleURL);let exit=null,maxSpeed=0,maxSurface=0,idle=0,longestIdle=0,maxRope=0,bounds=[],seen=new Set(),entered=false;const layers=geometry?depthLayers(d):null,preflight=geometry?initialGeometry(d,s):null,watch=globalThis.ChainReaction.events.watch(s,d);const eventFrames=[],captured=new Set();const joints=[];s.world.impulseJoints.forEach(j=>joints.push(j));
 try{for(let i=0;i<Math.round(d.durationWindow[1]*240);i++){s.step();watch.sample();if(trace){for(const e of watch.report(false).events){const tick=e.kind==='contact'?e.contactTick:e.motionTick;if(tick===null||captured.has(e.id))continue;captured.add(e.id);const a=s.bodies.get(e.from),b=s.bodies.get(e.to),points=[];for(let ai=0;ai<a.numColliders();ai++)for(let bi=0;bi<b.numColliders();bi++)s.world.contactPair(a.collider(ai),b.collider(bi),m=>{for(let k=0;k<m.numSolverContacts();k++){const q=m.solverContactPoint(k);if(q)points.push({x:q.x,y:q.y,z:d.parts.find(p=>p.id===e.to).z||0});}});if(!points.length){const q=b.translation();points.push({x:q.x,y:q.y,z:d.parts.find(p=>p.id===e.to).z||0});}eventFrames.push({id:e.id,tick,time:tick/240,points,poses:s.state().filter(p=>p.id===e.from||p.id===e.to)});}}let active=0;for(const p of d.parts){if(p.fixed)continue;const b=s.bodies.get(p.id),pos=b.translation(),v=b.linvel(),angle=b.rotation(),ca=Math.cos(angle),sa=Math.sin(angle);maxSpeed=Math.max(maxSpeed,Math.sqrt(v.x*v.x+v.y*v.y));let radius=0;const cells=p.colliders||[{...p,x:0,y:0,angle:0}];for(const c of cells){const x=pos.x+(c.x||0)*ca-(c.y||0)*sa,y=pos.y+(c.x||0)*sa+(c.y||0)*ca,theta=angle+(c.angle||0),co=Math.abs(Math.cos(theta)),si=Math.abs(Math.sin(theta));const rx=c.shape==='ball'?c.radius:co*c.width/2+si*c.height/2,ry=c.shape==='ball'?c.radius:si*c.width/2+co*c.height/2;radius=Math.max(radius,Math.sqrt((c.x||0)**2+(c.y||0)**2)+(c.shape==='ball'?c.radius:Math.sqrt(c.width*c.width+c.height*c.height)/2));if(p.id===d.entryId&&!entered&&(mirrored?x+rx<=16:x-rx>=0))entered=true;if(p.id!==d.exitId&&(p.id!==d.entryId||entered)&&(x-rx<-.025||x+rx>16.025||y-ry<-.025||y+ry>9.025)&&!seen.has(p.id)){seen.add(p.id);bounds.push({id:p.id,tick:s.tick,x,y,rx,ry});}}
 const surface=Math.sqrt(v.x*v.x+v.y*v.y)+Math.abs(b.angvel())*radius;if(d.path.includes(p.id))active=Math.max(active,surface);maxSurface=Math.max(maxSurface,surface);}
 idle=active<thresholds.minimumPathSurfaceSpeed?idle+1:0;longestIdle=Math.max(longestIdle,idle);
 for(let j=0;j<joints.length;j++)if(d.joints[j].type==='rope'){const q=joints[j];const point=(body,a)=>{const p=body.translation(),t=body.rotation(),c=Math.cos(t),sn=Math.sin(t);return {x:p.x+c*a.x-sn*a.y,y:p.y+sn*a.x+c*a.y};};const a=point(q.body1(),q.anchor1()),b=point(q.body2(),q.anchor2());maxRope=Math.max(maxRope,Math.sqrt((a.x-b.x)**2+(a.y-b.y)**2)/d.joints[j].length);}
 const b=s.bodies.get(d.exitId),p=b.translation(),v=b.linvel();if(mirrored?p.x<=0:p.x>=16){const vx=mirrored?-v.x:v.x,spin=mirrored?-b.angvel():b.angvel();exit={tick:s.tick,time:s.tick/240,x:p.x,y:p.y,vx,vy:v.y,spin,residual:Math.abs(spin+vx/.15625)};break;}}
 const events=watch.report(),failures=[];if(preflight&&!preflight.pass)failures.push('initial-overlap');if(layers&&!layers.pass)failures.push('depth-layers');if(!exit)failures.push('no-exit');else{if(exit.time<d.durationWindow[0]||exit.time>d.durationWindow[1])failures.push('duration');if(exit.vx<3.92||exit.vx>4.08||exit.y<1.15225||exit.y>1.16025||Math.abs(exit.vy)>.2||exit.residual>.5)failures.push('emit');}if(!events.pass)failures.push('causality');if(bounds.length)failures.push('plot-escape');if(maxSurface>thresholds.velocityCap)failures.push('velocity-cap');if(longestIdle/240>1.5)failures.push('dead-time');if(maxRope>1.01)failures.push('rope-stretch');return {pass:failures.length===0,failures,exit,maxSpeed,maxSurface,longestIdle:longestIdle/240,maxRope,bounds,events,preflight,layers,armed:d.parts.map(p=>({id:p.id,x:p.x,y:p.y,angle:p.angle||0})),spent:s.state(),eventFrames,snapshotHash:hash(s.snapshot())};}finally{s.dispose();}}
